#!/bin/bash
###############################################################################
# Script Name  : battery-check
# Description  : Display charge and health statics of a laptop battery
# Dependencies : None
# Arguments    : None
# Author       : Richard B. Romig, 28 Jul 2020
# Email        : rick.romig@gmail.com
# Comments     : Batttery health based on a script by Elias W (eliasw4u on Ezeetalk.com)
#              : Battery charge based on a script by Luke Smith (https://lukesmith.xyz)
#              : Supports multiple batteries.
# TODO (Rick)  :
###############################################################################
# Copyright (C) 2020, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Variables ##

readonly SCRIPT=$(basename "$0")
readonly VERSION="0.2.2"
readonly UPDATED="07 Aug 2020"

## Functions ##

function die()
{
  local MSG="$1"	    # message
  local EC=${2-1}	    # default exit status 1
  echo -e "\e[91mERROR:\e[0m $MSG" >&2
  exit "$EC"
}

battery_status()
{
  echo -e "\n\e[33mBattery charge:\e[0m"
  [ -f "$BATTERY/status" ] || die "Problem with the battery! Replace it!"
  BAT_STATUS=$(awk '{print $1}' "$BATTERY/status")
  [ -f "$BATTERY/capacity" ] || die "Problem with the battery! Replace it!"
  BAT_CHARGE=$(awk '{print $1}' "$BATTERY/capacity")
  [ "$BAT_STATUS" = "Discharging" ] && [ "$BAT_CHARGE" -le 25 ] && WARN="\U26A0\UFE0F"
  echo -e "\t\e[92mStatus:\e[0m $BAT_STATUS"
  echo -e "\t\e[92mCharge:\e[0m $BAT_CHARGE%  $WARN"
}

battery_capacity()
{
  if [ -f "$BATTERY/charge_full" ]; then
    ACTUAL_FULL="charge_full"
    UNIT="Ah"
  else
    ACTUAL_FULL="energy_full"
    UNIT="Wh"
  fi

  if [ -f "$BATTERY/charge_full_design" ]; then
    DESIGN_FULL="charge_full_design"
  else
    DESIGN_FULL="energy_full_design"
  fi

  ACTUAL_MAX=$(awk 'NF{print $1/1000000}' OFMT="%2.2f" "$BATTERY/$ACTUAL_FULL")
  DESIGN_MAX=$(awk 'NF{print $1/1000000}' OFMT="%2.2f" "$BATTERY/$DESIGN_FULL")
  INT_DES="${DESIGN_MAX%%.*}"
  INT_ACT="${ACTUAL_MAX%%.*}"
  if [ "$INT_DES" -eq 0 ] || [ "$INT_ACT" -eq 0 ]; then
    CAP_PERCENT="0"
  else
    CAP_PERCENT=$(echo "100/${DESIGN_MAX}*${ACTUAL_MAX}" | bc -l)
  fi
  BAT_HEALTH=$(echo "$CAP_PERCENT" | awk 'NF{print $1/1}' OFMT="%2.2f")

  echo -e "\n\e[33mBattery health:\e[0m"
  echo -e "\t\e[92mDesign capacity:\e[0m $DESIGN_MAX $UNIT"
  echo -e "\t\e[92mActual capacity:\e[0m $ACTUAL_MAX $UNIT"
  echo -e "\t\e[92mBattery health:\e[0m  $BAT_HEALTH%"
  battery_condition "$CAP_PERCENT"
}

battery_condition()
{
  CAP_PCT="$1"
  C_PCT="${CAP_PCT%%.*}"
  if [ "$C_PCT" -eq 0 ]; then
    WARN_LEVEL=0
  else
    WARN_LEVEL=$(echo "$CAP_PCT" | awk 'NF{print $1/1}' OFMT="%.0f")
  fi

  if [ "$WARN_LEVEL" -le "0" ]; then
    echo -e "\t\U26D4\e[31m  Replace the Battery!\e[0m \U26D4 "
  elif [ "$WARN_LEVEL" -le "35" ]; then
    echo -e "\t\U26D4\e[31m  The battery should be replaced.\e[0m \U26D4 "
  elif [ "$WARN_LEVEL" -le "65" ]; then
    echo -e "\t\U26A0\UFE0F\e[33m  The battery is getting weak.\e[0m \U26A0\UFE0F "
  else
    echo -e "\e[32m\tThe battery is in good condition.\e[0m"
  fi
}

## Execution ##

clear

for BATTERY in /sys/class/power_supply/BAT?
do
  echo -e "\e[1;33mBattery Status\e[0m"
  if [ "$BATTERY" = "/sys/class/power_supply/BAT?" ]; then
    echo -e "\n\e[91mNo battery detected.\e[0m"
  else
    echo -e "\n\e[33mBattery:\e[0m ${BATTERY##*/}"
    battery_status
    battery_capacity
  fi
done
echo -e "\n$SCRIPT v$VERSION (Updated: $UPDATED)\n"

exit
