#!/usr/bin/env bash
#############################################################################
# Script Name  : catless
# Description  : view text file with less or cat based on terminal window size.
# Dependencies : functionlib
# Arguments    : $1 -> file to be viewed
# Author       : Copyright (C) 2020, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.com
# Crated       : 02 Jan 2020
# Updated      : 30 Sep 2024
# Comments     : Checks to see if passed argument is a valid text or json file.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
#############################################################################
# Copyright © 2020, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Variables ##

script=$(basename "$0"); readonly script
readonly version="4.7.24274"

## Functions ##

help() {
  local errcode updated
  errcode="${1:-2}"
  updated="30 Sep 2024"
  cat << END_HELP
${orange}$script${normal} v$version (updated $updated)
Displays a text file using either cat or less depending the number of lines in
the file and the number of rows in the current terminal window. Less is used when
the number of lines is greater than the 87% of the rows, otherwise cat is used.

 ${green}Usage:${normal} $script filename [-h] [--help]

END_HELP
  exit "$errcode"
}

view_file() {
  local catmax filelines textfile
  textfile="$1"
  # Get 87% of screen
  catmax=$(( $(tput lines)*87/100 ))
  # Find the number of lines in the file
  filelines=$(wc -l "$textfile" | cut -d' ' -f1)
  # View the file
  box "File: $textfile" "*"
  if (( filelines <= catmax )); then
	  cat "$textfile"
	  over_line "$script $version" "*"
  else
	  less "$textfile"
	  echo "$script $version"
  fi
}

main() {
  if [[ $# -eq 0 ]]; then
    printf "%s No argument passed.\n" "$red_error" >&2
    help 1
  elif [[ "$1" = "-h" || "$1" = "--help" ]]; then
    help 0
  elif [[ ! -f "$1" ]]; then
    printf "%s %s not found.\n" "$red_error" "$1" >&2
    help 2
  elif [[ ! -s "$1" ]]; then
    printf "%s %s is an empty file.\n" "$red_error" "$1" >&2
    exit 1
  elif file -bL "$1" | grep -qEi "text|json"; then
    view_file "$1"
    exit 0
  else
    printf "%s %s is not a text file.\n" "$red_error" "$1" >&2
    help 1
  fi
}

## Execution ##

main "$@"
