#!/usr/bin/env bash
##########################################################################
# Script Name  : checkinit
# Description  : Checks what init system is being used.
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2022, Richard B. Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Crated       : 07 Sep 2022
# Updated      : 10 Oct 2024
# Comments     : partially based on code by Jake@Linux <https://gitlab.com/jped>
#              : The else in find_init will detect runit.
# License      : GNU General Public License, version 2.0
##########################################################################

# Copyright © 2023, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Functions ##

find_init() {
	local file data
	if [[ "$(/usr/bin/ps -p 1 | awk '/1 ?/ {print $NF}')" == "systemd" ]]; then
		printf "SystemD"
	elif [[ $(/sbin/init --version 2>/dev/null | awk '{print $1}') == "SysV" ]]; then
		printf "SysV"
	elif [[ -f /sbin/openrc ]]; then
		printf "OpenRC"
	else
		file='/proc/1/comm'
		if [[ -r "$file" ]]; then
			read -r data < "$file"
			printf '%s' "${data%% *}"
	  else
	 		printf '?'
		fi
  fi
}

main() {
	local script version
	script=$(basename "$0")
	version="1.5.24284"
	printf "Init System: %s \n" "$(find_init)"
	printf "%s v%s\n" "$script" "$version"
	exit
}

## Execution ##

main "$@"
