#!/usr/bin/env bash
###############################################################################
# Script Name  : check-updates
# Description  : check for updates and install if necessary.
# Dependencies : apt-get (optional: nala, flatpak, cinnamon-spice-updater)
# Arguments    : see help()
# Author       : Copyright (C) 2018, Richard Romig, Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Crated       : 08 Dec 2018
# Updated      : 13 Apr 2025
# Comments     : For Debian/Ubuntu-based Linux distributions
#              : apt-get is better suited than apt for use in scripts.
#              : Lists available updates. Updates can be deferred.
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

set -eu

## Global Variables ##

script=$(basename "$0"); readonly script
readonly version="7.0.25103"
SECONDS=0

## Functions ##

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
cleanup() {
  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
}

help() {
	local errcode="${1:-2}"
  local updated="10 Apr 2025"
	cat << _HELP_
${orange}$script${normal} $version, Upated: $updated
Performs a system update using Apt or Nala.

${green}Usage:${normal} $script [OPTION]

${orange}Available options:${normal}
  -a    Perform a system upgrade using apt-get
  -h    Show this help message and exit
  -n    Perform a system upgrade using nala
${orange}Notes:${normal}
  If nala is not installed, defers to using apt-get
_HELP_
  exit "$errcode"
}

check_disk_space() {
	local df_stats r_size r_used r_perc r_avail
	df_stats=$(df -h / | awk 'NR==2 {print $2,$3,$4,$5}')
	r_size=$(echo "$df_stats" | cut -d ' ' -f1)
	r_used=$(echo "$df_stats" | cut -d ' ' -f2)
	r_perc=$(echo "$df_stats" | cut -d ' ' -f4)
	r_avail=$(echo "$df_stats" | cut -d ' ' -f3)
  printf "\nDisk space used (root): %s / %s %s used, %s available.\n" "$r_used" "$r_size" "$r_perc" "$r_avail"
}

check_reboot_required() {
  if [[ -f /var/run/reboot-required || -f /run/reboot-required ]]; then
    cat /var/run/reboot-required.pkgs
    printf "\n%sREBOOT REQUIRED%s\n" "$orange" "$normal"
    if default_no "Do you want to reboot now?"; then
      sudo reboot
    else
      printf "\n%s Please remember to reboot your system as soon as possible.\n" "$RED_WARNING"
    fi
  fi
}

update_apt_cache() {
  local cache_file current_time updated_time time_diff threshold
  cache_file="/var/cache/apt/pkgcache.bin"
  current_time=$(date +%s)
  updated_time=$(stat -c%Y "$cache_file")
  time_diff=$(( current_time - updated_time ))
  # threshold values: 86400 = 24 hours, 43200 = 12 hours, 21600 = 6 hours 10800 = 3 hours
  threshold=10800
  if [[ "$time_diff" -le "$threshold" ]]; then
    printf "%sApt cache is up to date.%s\n" "$orange" "$normal"
  else
    printf "%sUpdating apt cache...%s\n" "$orange" "$normal"
    sudo apt-get update
  fi
}

install_updates() {
  printf "\n%sInstalling updates...%s\n" "$orange" "$normal"
  sudo apt-get dist-upgrade -yy
}

clean_apt_cache() {
  printf "\n%sCleaning up apt cache...%s\n" "$orange" "$normal"
  sudo apt-get autoclean
}

remove_orphans() {
  local npkgs
  # npkgs=$(apt-get autoremove -s | grep "^[[:digit:]]\+ upgraded" | cut -d' ' -f6)
  npkgs=$(apt-get autoremove -s | awk '$2 == "upgraded," {print $6}')
  printf "\n%sRemoving orphaned packages...%s\n" "$orange" "$normal"
  if [[ "$npkgs" -gt 0 ]]; then
    sudo apt-get autoremove -yy
  else
    printf "No packages to be removed.\n"
  fi
}

purge_rc_packages() {
  local rcpkg
  printf "\n%sPurging obsolete configuration files..%s\n" "$orange" "$normal"
  if dpkg -l | grep -c '^rc' > /dev/null; then
    for rcpkg in $(dpkg --list | awk '/^rc/ {print $2}'); do
      printf "Purging %s...\n" "$rcpkg"
      sudo apt-get remove --purge "$rcpkg" -yy
    done
  else
    printf "No packages in the 'rc' state.\n"
  fi
}

update_complete() {
  local num_updates="$1"
  printf "\n%sUpdate complete. %d" "$orange" "$num_updates"
  (( num_updates > 1 )) && printf  " updates were" || printf  " update was"
  printf " installed.%s\n" "$normal"
}

defer_updates() {
  local num_updates="$1"
  printf "\n%sNo updates installed. %d" "$orange" "$num_updates"
  (( num_updates > 1 )) && printf " updates were" || printf " update was"
  printf " deferred.%s\n" "$normal"
}

update_flatpak() {
  local fp_count
  fp_count=$(flatpak list | wc -l)
  printf "\n%sFlatpak:%s\n" "$orange" "$normal"
  if [[ "$fp_count" -gt 0 ]]; then
    printf "User installations...\n"
    flatpak update --user --noninteractive --force-remove --assumeyes
    printf "System-wide installations...\n"
    sudo flatpak update --system --noninteractive --force-remove --assumeyes  2> /dev/null
    # printf "\n"
  else
    printf "No Flatpaks installed.\n"
  fi
}

update_spices() {
  printf "\n%sCinnamon Spices:%s\n" "$orange" "$normal"
  cinnamon-spice-updater --update-all
}

nala_update() {
  printf "%sChecking for updates...%s\n" "$orange" "$normal"
  sudo nala upgrade
  if default_no "Run autoremove/autopurge?"; then
    printf "\n%sRemoving orphaned packages...%s\n" "$orange" "$normal"
    sudo nala autoremove
    printf "\n%sPurging obsolete configuration files..%s\n" "$orange" "$normal"
    sudo nala autopurge --config
  else
    printf "Autoremove and autopurge deferred.\n"
  fi
  printf "\n"
}

apt_update() {
  local nupd #summary
  printf "%sChecking for updates...%s\n" "$orange" "$normal"
  update_apt_cache
  nupd=$(count_updates)
  if (( nupd > 0 )); then
    printf "%sSummary:%s\n" "$orange" "$normal"
    sed -ne '/^Calculating/,/newly/p' "$tmp_file" | sed '1d'
    apt_menu "$nupd"
  else
    printf "%sSummary:%s\n" "$orange" "$normal"
    sed -ne '/^Calculating/,/newly/p' "$tmp_file" | sed '1d'
  fi
}

count_updates() {
	local field1 field2 field3
	local -i count=0
	field1=$(awk '$8 == "remove" {print $1}' "$tmp_file")
	field2=$(awk '$8 == "remove" {print $3}' "$tmp_file")
	field3=$(awk '$8 == "remove" {print $6}' "$tmp_file")
	count=$((field1 + field2 + field3))
	echo "$count"
}

apt_menu() {
  local nupd options _opt
	nupd="$1"
	COLUMNS=40
	printf "\n%s%sUpdate options:%s\n" "$underline" "$green" "$normal"
	PS3="Choose an option: "
	options=(
		"Install updates."
		"Install updates and clean cache."
		"Install updates and remove orphaned packages."
		"Install updates, clean cache, and remove orphaned packages."
		"Defer updates until later."
	)
	select _opt in "${options[@]}"; do
		case $REPLY in
			1 )
				install_updates
				update_complete "$nupd"
				break
			;;
			2 )
				install_updates
				clean_apt_cache
				update_complete "$nupd"
				break
			;;
			3 )
				install_updates
				remove_orphans
				purge_rc_packages
				update_complete "$nupd"
				break
			;;
			4 )
				install_updates
				clean_apt_cache
				remove_orphans
				purge_rc_packages
				update_complete "$nupd"
				break
			;;
			5 )
				defer_updates "$nupd"
				break
			;;
			* )
				printf "%sInvalid option!%s Select 1..%d\n" "$lightred" "$normal" "${#options[@]}" >&2
		esac
	done
}

show_header() {
  local local_host="${HOSTNAME:-$(hostname)}"
  clear
  cat << _HEADER_
${bold}${orange}$script $version
System: $local_host ($(local_ip))
Distro: $(get_distribution)
Kernel: $(uname -sr)${normal}
_HEADER_
}

main() {
  local noOpt opt optstr
	noOpt=1
	optstr=":ahn"
	while getopts "$optstr" opt; do
    case "$opt" in
      a )
        tmp_file=$(mktemp -q) || die "Failed to create temporary file." 1
        trap cleanup EXIT
        apt-get dist-upgrade -s > "$tmp_file"
        show_header
        # cat "$tmp_file"
        check_disk_space
        sudo_login 2
        apt_update
      ;;
      h )
        help 0
      ;;
      n )
        show_header
        check_disk_space
        sudo_login 2
        if exists nala; then nala_update; else apt_update; fi
      ;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help 2
		esac
		noOpt=0
  done
	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
	shift "$(( OPTIND - 1 ))"
  exists cinnamon-spice-updater && update_spices
  if exists flatpak; then update_flatpak; else printf "\nFlatpak is not installed.\n"; fi
  check_disk_space
  over_line "Update completed in $(format_time $SECONDS)"
  check_reboot_required
  over_line "$script $version"
  exit
}

## Execution ##

main "$@"
