#!/bin/bash
#####################################################################
# Script Name  : chkupdates
# Description  : check to see if updates are available
# Dependencies : apt, apt-get, grep, cut, sudo
# Arguments    : none
# Author       : Richard Romig, 08 December 2018
# Email        : rick.romig@gmail.com
# Comment      : Lists available updates if there are any
#####################################################################
# Copyright (C) 2018  Richard Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
#####################################################################
echo "Checking for updates..."
sudo apt-get update
numug=$(apt-get upgrade -s | grep -P '^\d+ upgraded' | cut -d" " -f1) > /dev/null 2>&1
echo "$numug updates available."
if [ "$numug" -gt 0 ]; then
	echo "Available updates..."
	apt list --upgradeable
fi
exit 0
