#!/bin/bash
###############################################################################
# Script Name  : chkupdates
# Description  : check to see if updates are available
# Dependencies : apt, cut, grep, select, sudo
# Arguments    : none
# Author       : Richard Romig, 08 December 2018
# Email        : rick.romig@gmail.com
# Comments     : Lists available updates, if any.
#              : For Debian/Ubuntu-based Linux distributions
# Last updated : 6 Feb 2020
###############################################################################
# Copyright (C) 2018  Richard Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
###############################################################################

set -e

install_updates()
{
  echo -e "\n\e[1;33mInstalling updates ...\e[0m"
  sudo apt full-upgrade -yy
}

clean_cache()
{
  echo -e "\n\e[1;33mCleaning up apt cache ...\e[0m"
  sudo apt autoclean
}

remove_orphans()
{
  echo -e "\n\e[1;33mRemoving orphaned packages ...\e[0m"
  sudo apt autoremove -yy
}

all_done()
{
  echo -e "\n\e[1;33mUpdate complete.\e[0m"
  echo "$NUPD updates installed."
  echo "Update completed in $(format_time $SECONDS)"
}

format_time()
{
  ET="$1"
  ((h=ET/3600))
  ((m=(ET%3600)/60))
  ((s=ET%60))
  printf "%02d:%02d:%02d\n" $h $m $s
}

VERSION="v1.2.2"
LHOST=$HOSTNAME

sudo ls > /dev/null 2>&1

SECONDS=0

clear
echo -e "\e[1;33mChkupdates $VERSION\e[0m"
echo -e "\e[1;33mChecking for updates on $LHOST...\e[0m"
sudo apt update

# Without the `2>/dev/null`, apt will display the following error message:
# `WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`

NUPD=$(apt upgrade -s 2>/dev/null | grep -P '^\d+ upgraded' | cut -d" " -f1)

if (( NUPD > 0 )); then
  apt list --upgradeable
  echo -e "\n\e[1;33mUpdate options:\e[0m"
  PS3="Choice: "
  OPTIONS=("Install updates" "Install updates and clean up" \
   "Install updates and remove orphaned packages" "Exit without updating")
  select OPT in "${OPTIONS[@]}"
  do
    case $OPT in
      "Install updates")
        install_updates
        all_done
        break
        ;;
      "Install updates and clean up")
        install_updates
        remove_orphans
        clean_cache
        all_done
        break
        ;;
      "Install updates and remove orphaned packages")
        install_updates
        remove_orphans
        all_done
        break
        ;;
      "Exit without updating")
        echo -e "\n\e[1;33m $NUPD updates available but not installed.\e[0m"
        echo "Script completed in $(format_time $SECONDS)"
        break
        ;;
      *)
        echo -e "\e[1;31mInvalid option! Try again.\e[0m" >&2
        ;;
    esac
  done
else
  echo "Script completed in $(format_time $SECONDS)"
fi

exit
