#!/bin/bash
###############################################################################
# Script Name  : clean-bin
# Description  : cleas ~/bin of ~ backup files and copies files recently
#              : created or modfied to a designated folder
# Dependencies : find, cp, pushd, popd, rm, wc
# Arguments    : none
# Author       : Richard Romig, 18 January 2019
# Email        : rick.romig@gmail.com
# Comments     :
###############################################################################
# Copyright (c) 2019  Richard Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
###############################################################################

# Variables

readonly VERSION="v1.2.3"
readonly UPDATED="13 Sep 2019"

# Directory variables

readonly HOMEDIR=$HOME
readonly CURDIR=$PWD
readonly BINDIR="$HOMEDIR/bin"
readonly SCRIPTDIR="$HOMEDIR/Documents/mosfanet/Scripts/bash/my-scripts/"
readonly FUNCDIR="$HOMEDIR/Documents/mosfanet/Scripts/bash/functions/"

# Functions

remove_tilde()
{
  find . -maxdepth 2 -type f -iname \*~ -print -exec rm {} \;
}

clear

# Change directory to ~/bin

[ "$CURDIR" != "$BINDIR" ] && pushd "$BINDIR" > /dev/null 2>&1

echo "Clean-bin v$VERSION (Updated $UPDATED)"
echo "Cleaning up $BINDIR directory..."

# Remove files ending with *~

NBU=$(find ./ -maxdepth 2 -type f -name \*~  | wc -l)

if (( NBU == 0 )); then
  echo $'\n'$"No backup files ending with '~' found in $BINDIR."
elif (( NBU == 1 )); then
  echo $'\n'$"Removing $NBU '~' backup file in $BINDIR."
  remove_tilde
else
  echo $'\n'$"Removing $NBU '~' backup files in $BINDIR."
  remove_tilde
fi

# Copy files that have been created or modified

echo $'\n'$"Backup files created or modified:"
OPTIONS=("Today" "In the last 24 hours" "In the last 2 days" "Exit the script")
PS3="Chose an option: "
select OPT in "${OPTIONS[@]}"
do
  case $OPT in
    "Today")
      echo $'\n'$"Scripts created or modified today:"
      find . -maxdepth 1 -type f -daystart -mtime -1 -print -exec cp -pu {} \
        "$SCRIPTDIR" \;
      echo "copied to $SCRIPTDIR"
      if [ -d "./functions" ]; then
        pushd ./functions > /dev/null 2>&1
        echo "Functions created or modified today:"
        find . -maxdepth 1 -type f -daystart -mtime -1 -print -exec cp -pu {} \
          $FUNCDIR \;
        echo "copied to $FUNCDIR"
        popd > /dev/null 2>&1
      fi
      break
      ;;
    "In the last 24 hours")
      echo $'\n'$"Scripts created or modified in the last 24 hours:"
      find . -maxdepth 1 -type f -mtime -1 -print -exec cp -pu {} "$SCRIPTDIR" \;
      echo "copied to $SCRIPTDIR"
      if [ -d "./functions" ]; then
        pushd ./functions > /dev/null 2>&1
        echo "Functions created or modified in the last 24 hours:"
        find . -maxdepth 1 -type f -mtime -1 -print -exec cp -pu {} $FUNCDIR \;
        echo "copied to $FUNCDIR"
        popd > /dev/null 2>&1
      fi
      break
      ;;
    "In the last 2 days")
      echo $'\n'$"Scripts created or modified in the last 2 days:"
      find . -maxdepth 1 -type f -mtime -2 -print -exec cp -pu {} "$SCRIPTDIR" \;
      echo "copied to $SCRIPTDIR"
      if [ -d "./functions" ]; then
        pushd ./functions > /dev/null 2>&1
        echo "Functions created or modified in the last 2 days:"
        find . -maxdepth 1 -type f -mtime -2 -print -exec cp -pu {} $FUNCDIR \;
        echo "copied to $FUNCDIR"
        popd > /dev/null 2>&1
      fi
      break
      ;;
    "Exit the script")
      echo "Exiting the script."
      break
      ;;
    *)
      echo "Invalid choice. Try again."
      ;;
  esac
done

# Return to the directory where you started

[ "$CURDIR" != "$BINDIR" ] && popd > /dev/null 2>&1

exit

