#!/bin/bash
#####################################################################
# Script Name  : clean-bin
# Description  : cleas ~/bin of ~ backup files  and copies files
#              : modfied in last 24 hours to designated folder
# Dependencies : find, xargs, cp, pushd, popd
# Arguments    : none
# Author       : Richard Romig, 18 January 2019
# Email        : rick.romig@gmail.com
# Comment      :
#####################################################################
# Copyright (C) 2019  Richard Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

# Variables

user=$USER
curdir=$PWD
scriptfolder="/home/$user/Documents/mosfanet/Scripts/bash/my-scripts/"

# Change directory to ~/bin

[ "$curdir" != "/home/$user/bin" ] && pushd "/home/$user/bin" > /dev/null

echo "Clean-bin -- Cleaning up /home/$user/bin directory..."

# Remove files ending with *~

nbu=$(find ./ -maxdepth 1 -type f -name \*~  | wc -l)

if [ "$nbu" -eq "0" ]; then
  echo "No '~' backup files ending with '~' found."
else
  echo "Cleaning up $nbu '~' backup files from /home/$user/bin..."
  find ./ -maxdepth 1 -type f -iname \*~ -print -exec rm {} \;
fi

# Copy files created or modified within the last 24 hours

echo "Copying new and updated files to $scriptfolder ..."
find ./ -maxdepth 1 -type f -mtime -1 -print -exec cp -pu {} "$scriptfolder" \;

# Return to the directory where you started

[ "$curdir" != "/home/$user/bin" ] && popd > /dev/null

exit
