#!/bin/bash
#####################################################################
# Script Name  : cleanbin
# Description  : cleas ~/bin of ~ backup files  and copies files 
#              : modfied in last 24 hours to designated folder
# Dependencies : find, xargs
# Arguments    : none
# Author       : Richard Romig, 18 January 2019
# Email        : rick.romig@gmail.com
# Comment      :
#####################################################################
# Copyright (C) 2019  Richard Romig
# Email: rick.romig@gmail.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

SCRIPTFOLDER="/home/rick/Documents/mosfanet/Scripts/bash/my-scripts/"

if [ $PWD != ~/bin ]; then
	pushd ~/bin
fi

echo "Cleaning up ~ backup files"
ls *~ > /dev/null 2>&1
if [ "$?" != "0" ]; then
     echo "No files ending with ~ found."
else
     ls *~
     rm *~
     echo "All files ending with ~ removed."
fi

echo "Copying new and updated files to $SCRIPTFOLDER."
find ./ -type f -mtime -1 -print -exec cp -pf {} $SCRIPTFOLDER \;
echo "Scripts modified in the last 24 hours copied to $SCRIPTFOLDER."

popd 2>/dev/null

exit 0
