#!/bin/bash
#####################################################################
# Script Name  : dos2linux
# Description  : converts DOS text files to Linux format
# Dependencies : sed
# Arguments    : file to be converted
# Author       : Richard Romig, 24 January 2019
# Email        : rick.romig@gmail.com
# Comment      : removes DOS carriage return '\r' characters
#####################################################################

# Copyright (C) <2019>  Richard Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

usage()
{
  echo "Usage: $SCRIPT <file>"
  exit 1
}

SCRIPT=$(basename "$0")
VERSION="1.0.4"
UPDATED="3 Jan 2020"

# check number of arguments

if [ -z "$1" ]; then
  echo -e "\e[1;41mError:\e[0m No argments passed." >&2
  usage
elif [ ! -f "$1" ]; then
  echo -e "\e[1;41mError:\e[0m $1 not found." >&2
  usage
else
  FILE=$1
fi

echo "$SCRIPT v$VERSION (Updated: $UPDATED)"
echo "Converts DOS text files to Linux format by removing carriage return characters."

# convert the file

echo "Removing the carriage return characters from $FILE while creating a backup"
echo "of the orginal file."
sed -i.bak -e 's/\r//g' "$FILE"

exit
