#!/usr/bin/env bash
#############################################################################
# Script Name  : install-brave
# Description  : installs the Brave broswer
# Dependencies : apt-transport-https, curl, libu2f-udev
# Arguments    : Ssee help function
# Author       : Copyright (C) 2019, Richard B. Romig
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 12 Dec 2019
# Updated      : 23 Feb 2025
# Comments     : For Debian, Ubuntu, Mint ... (Code from Brave's instructions)
#              : Brave is only supported on 64-bit AMD/Intel architectures (amd64/x86_64).
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
#############################################################################
#
# Copyright © 2019, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

script=$(basename "$0"); readonly script
readonly version="4.11.25054"
readonly brave_key="/usr/share/keyrings/brave-browser-archive-keyring.gpg"
readonly brave_list="/etc/apt/sources.list.d/brave-browser-release.list"

## Functions ##

brave_version() {
  brave-browser --version
}

install_brave() {
  local key_url list_url
  key_url="https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
  list_url="https://brave-browser-apt-release.s3.brave.com/ stable main"
  printf "Installing the Brave Browser ...\n"
  # Import the public key for verification of the APT repository
  sudo curl -fsSLo "$brave_key" "$key_url"
  # Add the repository
  echo "deb [signed-by=$brave_key arch=amd64] $list_url" | sudo tee "$brave_list" > /dev/null
  # Install Brave
  sudo apt-get update -qq
  sudo apt-get install brave-browser brave-keyring -yy
  printf "%s successfully installed.\n" "$(brave_version)"
}

remove_brave() {
	local apt_key="/etc/apt/trusted.gpg.d/brave-browser-release.gpg"
  printf "Uninstalling %s...\n" "$(brave_version)"
  sudo apt-get remove brave-browser brave-keyring -yy
  # Remove trusted keys
  if [[ -f "$apt_key" ]]; then
    sudo rm "$apt_key"
    sudo apt-key del C3D4E821 2>/dev/null #apt-key deprecated
  elif [[ -f "$brave_key" ]]; then
    sudo rm "$brave_key"
  fi
  # Remove brave-browser-release.list
  [[ -f "$brave_list" ]] && sudo rm "$brave_list"
  printf "Brave browser has been uninstalled.\n"
}

remove_configs() {
  local brave_cfg_dir brave_cache_dir
  brave_cfg_dir="${HOME}/.config/BraveSoftware"
  brave_cache_dir="${HOME}/.cache/BraveSoftware"
  printf "Removing local configuration and cache files...\n"
  [[ -d "$brave_cfg_dir" ]] && rm -rf "$brave_cfg_dir"
  [[ -d "$brave_cache_dir" ]] && rm -rf "$brave_cache_dir"
  printf "Brave local configuration and cache files have been removed.\n"
}

help() {
  local errcode updated
  errcode="${1:-2}"
	updated="23 Feb 2025"
  cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs/Removes the Brave browser

${green}Usage:${normal} $script [OPTION]

${orange}Available options:${normal}
  -h  Show this help message and exit.
  -i  Install the Brave Browser.
  -p  Remove the Brave Browser & purge configuration files.
  -r  Remove the Brave Browser & leave configuration files.
_HELP_
  exit "$errcode"
}

check_dependencies() {
  local packages=( apt-transport-https curl libu2f-udev )
  if [[ $(uname -m) == "x86_64" ]]; then
    printf "x86_64 - OK\n"
    sleep 2
    printf '\e[A\e[K'
	  check_packages "${packages[@]}"
  else
    die "System architecture is not 64-bit." 1
  fi
}

main(){
  local noOpt opt optstr
  noOpt=1
  optstr=":hipr"
  while getopts "$optstr" opt; do
    case "$opt" in
      h )
        help 0
      ;;
      i )
        exists brave-browser && leave "$(brave_version) is already installed."
        sudo_login 2
        printf "Installs/Removes the Brave browser.\n\n"
        check_dependencies
        install_brave
      ;;
      p )
        exists brave-browser || leave "Brave browser is not installed."
        sudo_login 2
        printf "Installs/Removes the Brave browser.\n\n"
        remove_brave
        remove_configs
      ;;
      r )
        exists brave-browser || leave "Brave browser is not installed."
        sudo_login 2
        printf "Installs/Removes the Brave browser.\n\n"
        remove_brave
      ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help 2
    esac
    noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  over_line "Sscript v$version"
  exit
}

## Execution ##

main "$@"
