#!/bin/bash
#####################################################################
# Script Name  : ip-info
# Description  : Displays IP information
# Dependencies : awk, ip, iwconfig, iwgetid, nmcli, wget
# Arguments    : None
# Author       : Richard Romig, 19 February 2019
# Email        : rick.romig@gmail.com
# Comment      : iwconfig may not show signal level for some wireless cards,
#              : noteably, Broadcom cards. See man iwconfig.
# TODO (rick)  :
###############################################################################

# Copyright (C) 2019, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Variables ##

readonly SCRIPT=$(basename "$0")
readonly VERSION="1.1.2"
readonly UPDATED="17 Apr 2020"

# Network interfaces

ETH_INT=$(/usr/bin/nmcli dev | awk '/ethernet/ { print $1 }')
WIFI_INT=$(/usr/bin/nmcli dev | awk '/wifi/ { print $1 }')

# IP addresses

PUBLIC_IP=$(/usr/bin/wget -qO- http://ipv4.icanhazip.com)
[ -n "$ETH_INT" ] && ETH_IP=$(/sbin/ip -o -4 addr show \
 | awk -v name="$ETH_INT" '$0~name { print $4" ("$2")" }')
[ -n "$WIFI_INT" ] && WIFI_IP=$(/sbin/ip -o -4 addr show \
 | awk -v name="$WIFI_INT" '$0~name { print $4" ("$2")" }')
[ -n "$WIFI_IP" ] && WIFI_SIG=$(/sbin/iwconfig "$WIFI_INT" \
 | awk -F'=' '/Signal/ { print $3 }')

# Display IP Information

echo $'\n'$"$SCRIPT v$VERSION"
echo "(Updated: $UPDATED)"
echo $'\n'$"IP Information"
echo "=============="
echo "Public IP:"
if [ -n "$PUBLIC_IP" ]; then
  echo -e "\t$PUBLIC_IP"
else
  echo -e "\tNo Internet address found."
fi
echo "Local IP:"
echo -en "\tEthernet: "
if [ -n "$ETH_INT" ] && [ -n "$ETH_IP" ]; then
  echo "$ETH_IP"
elif [ -n "$ETH_INT" ]; then
  echo "Not connected"
else
  echo "No device found."
fi
echo -en "\tWireless: "
if [ -n "$WIFI_INT" ] && [ -n "$WIFI_IP" ]; then
  echo "$WIFI_IP"
  echo -e "\t  SSID:   $(/sbin/iwgetid -r)"
  [ -n "$WIFI_SIG" ] && echo -e "\t  Signal: $WIFI_SIG"
elif [ -n "$WIFI_INT" ]; then
  echo "Not connected"
else
  echo "No device found."
fi
echo "Default Gateway:"
/sbin/ip route | awk '/default/ { print "\t"$5": "$3 }'
echo "DNS Servers:"
/usr/bin/nmcli dev show | awk '/IP4.DNS/ { printf "\t%s\n",$2 }'

exit
