#!/bin/bash
#####################################################################
# Script Name  : ipinfo.sh
# Description  : Displays IP information
# Dependencies : awk, ip, nmcli, wget
# Arguments    : None
# Author       : Richard Romig, 19 February 2019
# Email        : rick.romig@gmail.com
# Comment      :
#####################################################################

# Copyright (C) 2019, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Variables ##

readonly SCRIPT=$(basename "$0")
readonly VERSION="1.0.4"
readonly UPDATED="13 Sep 2019"

# Network interfaces

ETHINT=$(/usr/bin/nmcli dev | awk '/ethernet/ { print $1 }')
WIFIINT=$(/usr/bin/nmcli dev | awk '/wifi/ { print $1 }')

# IP addresses

PUBLICIP=$(/usr/bin/wget -qO- http://ipv4.icanhazip.com)
ETHIP=$(/sbin/ip -o -4 addr show | awk -v name="$ETHINT" \
        '$0~name { print $4" ("$2")" }')
WIFIIP=$(/sbin/ip -o -4 addr show | awk -v name="$WIFIINT" \
         '$0~name { print $4" ("$2")" }')

# Display IP Information

echo $'\n'$"$SCRIPT v$VERSION (Updated: $UPDATED)"
echo $'\n'$"IP Information"
echo "=============="
echo "Public IP:"
echo -e "\t$PUBLICIP"
echo "Local IP:"
if [ -n "$ETHINT" ] && [ -n "$ETHIP" ]; then
  echo -e "\tEthernet: $ETHIP"
elif [ -n "$ETHINT" ]; then
  echo -e "\tEthernet: Not connected"
else
  echo -e "\tEthernet: No device found."
fi
if [ -n "$WIFIINT" ] && [ -n "$WIFIIP" ]; then
  echo -e "\tWireless: $WIFIIP"
elif [ -n "$WIFIINT" ]; then
  echo -e "\tWireless: Not connected"
else
  echo -e "\tWireless: No device found."
fi
echo "Default Gateway:"
/sbin/ip route | awk '/default/ { print "\t"$5": "$3 }'
echo "DNS Servers:"
/usr/bin/nmcli dev show | awk '/IP4.DNS/ { printf "\t%s\n",$2 }'

exit

