#!/usr/bin/env bash
##########################################################################
# Script Name  : iru-micro
# Description  : Installs, updates, and removes the Micro CLI text editor.
# Dependencies : gdebi, wget
# Arguments    : [-b] [-h] [-i] [-r] [-s] [-u] (See help function)
# Author       : Copyright (C) 2022, Richard B. Romig, 10 Jan 2022
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 10 Jan 2022
# Updated      : 14 Jan 2025
# Comments     : -u option updates installed version only. Does not do initial install.
#              : Due to changes in the micro repoisitory, scripts installs from a .tar.gz file.
#              : Version 2.0.13 is the latest version compatible with Debian Bullseye and older.
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################
#
# Copyright © 2023, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Variables ##

script=$(basename "$0"); readonly _script
readonly version="6.4.25014"
readonly gh_url="https://github.com/zyedidia/micro/releases"
readonly cfg_d="$HOME/.config/micro"

## Functions ##

# shellcheck disable=SC2317 # Don't warn about unreachable commands in this function
# ShellCheck may incorrectly believe that code is unreachable if it's invoked by variable name or in a trap.
cleanup() {
  [[ -d "$tmp_dir" ]] && rm -rf "$tmp_dir"
  [[ -f "$tmp_file" ]] && rm -f "$tmp_file"
}

check_dependencies() {
  local packages=( gdebi wget )
  check_packages "${packages[@]}"
}

check_distro() {
  local codename
  codename=$(lsb_release -c -s)
  case "$codename" in
    bullseye ) return "$FALSE" ;;
    * ) return "$TRUE"
  esac
}

micro_version() {
  micro --version | awk '/Version/ {print $NF}'
}

newest_version() {
  wget -qO "$tmp_file" "$gh_url"
  if check_distro; then
    new_ver=$(sed 's/\// /g' "$tmp_file" | grep -Ev 'beta|-rc' | awk '/download/ && /linux/ {print $7;exit}' | sed 's/^v//')
  else
    new_ver="2.0.13"
  fi
  echo "$new_ver"
}

compare_versions() {
  local cur_ver
  cur_ver=$(micro_version)
  if [[ "$cur_ver" == "$new_ver" ]]; then
    printf "%sMicro %s is the current version. No update required.%s/n" "$lightyellow" "$cur_ver" "$normal"
    check_distro || printf "Bat %s is the latest version compatible with %s./n" "$new_ver" "$(get_distribution)"
  else
    echo "${lightyellow}Installed version of Micro is $cur_ver, updating to $new_ver...${normal}"
    check_distro || printf "Bat %s is the latest version compatible with %s./n" "$new_ver" "$(get_distribution)"
    install_micro
  fi
}

install_micro() {
  local new_pkg="micro-${new_ver}-linux64.tar.gz"
  printf "Downloading Micro %s from the zyedidia GitHub repository..." "$new_ver"
  dots "."
  wget -q -P "$tmp_dir/" "$gh_url/download/v$new_ver/$new_pkg"
  kill "$!";printf "done\n";tput cnorm
  printf "Installing Micro %s...\n" "$new_ver"
  tar -xzvf "$tmp_dir/$new_pkg" -C "$tmp_dir/"
  sudo cp -v "$tmp_dir/micro-$new_ver"/micro /usr/bin/
  sudo cp -v "$tmp_dir/micro-$new_ver"/micro.1 /usr/share/man/man1/
  check_package xclip
  printf "Micro %s installed.\n" "$(micro_version)"
}

remove_micro() {
  cur_ver=$(micro_version)
  printf "Removing the Micro CLI text editor...\n"
  sudo dpkg --remove -y micro
  [[ -d "$cfg_d" ]] && rm -rf "$cfg_d"
  [[ -d /root/.config/micro ]] && sudo rm -rf /root/.config/micro
  printf "Micro %s and configuration files have been removed.\n" "cur_ver"
}

apply_settings() {
  [[ -d "$cfg_d" ]] || mkdir -p "$cfg_d"
  printf "Applying Micro settings...\n"
  settings
  printf "Micro setttings applied.\n"
}

settings() {
  cat <<- _SETTINGS_ > "$cfg_d/settings.json"
{
  "colorscheme": "atom-dark",
  "diffgutter": true,
  "rmtrailingws": true,
  "softwrap": true,
	"tabsize": 2,
  "wordwrap": true
}
_SETTINGS_
  printf "Micro settings.json created.\n"
}

apply_bindings() {
  [[ -d "$cfg_d" ]] || mkdir -p "$cfg_d"
  printf "Applying Micro keybindings...\n"
  bindings
  printf "Micro keybindings applied.\n"
}

bindings() {
  cat << _BINDINGS_ > "$cfg_d/bindings.json"
{
  "Alt-/": "lua:comment.comment",
  "CtrlUnderscore": "lua:comment.comment",
  "Alt-s": "Save,Quit",
  "Ctrl-Alt-v": "VSplit",
  "Ctrl-Alt-z": "HSplit"
}
_BINDINGS_
  printf "micro bindings.json created.\n"
}

help() {
  local errcode updated
	errcode="${1:-2}"
	updated="14 Jan 2025"
  cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs, configures, updates, or removes the Micro CLI text editor.

${green}Usage:${normal} $_script [OPTION]

${orange}Available options:${normal}
  -b  Installs/updates the Micro key-bindings json file.
  -h  Displays help.
  -i  Installs the Micro CLI text editor.
  -r  Removes the Micro CLI text editor from the system.
  -s  Installs/updates the Micro settings json file.
  -u  Updates the Micro CLI text editor to the latest version.
_HELP_
  exit "$errcode"
}

main() {
	local noOpt opt optstr new_ver
	noOpt=1
	optstr=":bhirsu"
	check_dependencies
	while getopts "$optstr" opt; do
		case "$opt" in
			b )
				exists micro || leave "Micro is not installed."
				apply_bindings
			;;
			h )
				help 0
			;;
			i )
				exists micro && leave "Micro $(micro_version) is already installed."
				tmp_file=$(mktemp) || die "Failed to create temporary file." 1
				tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
				trap cleanup EXIT
				sudo_login 2
				new_ver="$(newest_version)"
				printf "%sInstalling Micro version %s...%s\n" "$lightyellow" "$new_ver" "$normal"
				install_micro
				apply_settings
				apply_bindings
			;;
			r )
				exists micro || leave "Micro is not installed."
				sudo_login 2
				remove_micro
			;;
			s )
				exists micro || leave "Micro is not installed."
				apply_settings
			;;
			u )
				exists micro || leave "Micro is not installed."
				tmp_file=$(mktemp) || die "Failed to create temporary file." 1
				tmp_dir=$(mktemp -d) || die "Failed to create temporary directory." 1
				trap cleanup EXIT
				sudo_login 2
				new_ver="$(newest_version)"
				[[ "$new_ver" ]] || die "No download available. Try again later." 1
				compare_versions
			;;
			? )
				printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help 2
		esac
		noOpt=0
		done
	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
	shift "$(( OPTIND - 1 ))"
	over_line "$script v$version"
	exit
}

## Execution ##

main "$@"
