#!/usr/bin/env bash
##########################################################################
# Script Name  : laptoplid
# Description  : Settings to close laptop lid without suspend
# Dependencies : ~/bin/files/laptoplid.sed
# Arguments    : None
# Author       : Copyright (C) 2020, Richard B. Romig
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 22 Oct 2020
# Updated      : 14 Jan 2025
# Comments     :
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
##########################################################################
#
# Copyright © 2020, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

modify_logind() {
  local logind_conf="/etc/systemd/logind.conf"
  local sed_file="$HOME/bin/files/laptoplid.sed"
  if [[ -f "$sed_file" ]]; then
    sudo_login 2
    printf "Allows a laptop lid to be closed without going into suspend mode.\n"
    printf "Modifying %s and restarting systemd-logind service.\n" "$logind_conf"
    sudo sed -i.bak -f "$sed_file" "$logind_conf"
    sudo systemctl restart systemd-logind.service
    printf "%s modified and backup created.\n" "$logind_conf"
  else
    printf  "A required file, %s, was not found. Operation canceled" "$(basename "$sed_file")"
  fi
}

main() {
  local lhost script version
  lhost="${HOSTNAME:=-$(hostname)}"
  script=$(basename "$0")
  version="4.3.25014"
  if is_laptop; then
    modify_logind
  else
    printf "%s is not a laptop. Operation canceled.\n" "$lhost"
  fi
  over_line "$script v$version"
  exit
}

## Execution ##

main "$@"
