#!/usr/bin/env bash
#####################################################################
# Script Name  : laptop-utils
# Description  : Installs laptop-specific utilities
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2023, Richard Romig, LudditeGeek
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 23 Mar 2023
# Updated      : 14 Jan 2025
# Comments     : Based on a script by Joe Collins at EzeeLinux.com
# TODO (rick)  :
# License      : GNU General Public License, version 2.0
###############################################################################

# Copyright © 2023, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib
# shellcheck disable=SC1091

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2; exit 1
fi

## Global Variables ##

script=$(basename "$0"); readonly script
readonly version="6.3.25014"

## Funtions ##

intro() {
  cat << _INTRO_
Installs laptop-specific utilities:
 * Thermald - monitors and controls temperature.
 * ACPI - checks the state of ACPI devices.
 * TLP - advanced power management to maximize battery life.
 * Touchpad Indicator - utility to enable/disable the touchpad.

_INTRO_
}

help() {
  local errcode="${1:-2}"
  local updated="21 Sep 2024"
  intro
  cat << _HELP_
${orange}$script${normal} $version ($updated)
Installs laptop-specific utlities.

${green}Usage:${normal} $script [OPTION]

${orange}Available options:${normal}
  -h  Display help.
  -i  Install laptop utilities.
  -l  List installed utilities.
  -s  Start TLP service

_HELP_
  intro
  exit "$errcode"
}

installed() {
  local package="$1"
  dpkg -l "$package" > /dev/null 2>&1 && return "$TRUE" || return "$FALSE"
}

install_thermald() {
  if installed thermald; then
    printf "Thermald is already installed.\n"
  elif in_repos thermald; then
    sudo apt-get install thermald -yy
    printf "Thermald installed.\n"
  else
    printf "Thermald was not installed.\n"
  fi
}

install_acpi() {
  if installed acpi; then
    printf "ACPI is already installed.\n"
  elif in_repos acpi; then
    sudo apt-get install acpi -yy
    printf "ACPI installed.\n"
  else
    printf "ACPI was not installed.\n"
  fi
}

install_touchpad_indicator() {
  if installed touchpad-indicator; then
    printf "Touchpad Indicator is already installed.\n"
  elif in_repos touchpad-indicator; then
    sudo apt-get install touchpad-indicator -yy
    printf "Touchpad Indicator installed.\n"
  else
    printf "Touchpad Indicator was not available.\n"
  fi
}

install_tlp() {
  if installed tlp && installed tlp-rdw; then
    echo "TLP is already installed."
  elif in_repos tlp; then
    sudo apt-get install tlp tlp-rdw -yy
    start_tlp_service
    printf "TLP installed.\n"
  else
    printf "TLP was not installed.\n"
  fi
}

tlp_status() {
  local status=1
  installed tlp || leave "TLP is not installed."
  if is_systemd; then
    systemctl status tlp | grep -qw active && status=0
  elif is_sysv; then
    tlp-stat -s | grep -qw enabled && status=0
  fi
  if [[ "$status" -eq 1 ]]; then
    printf "Starting TLP service\n"
    start_tlp_service
  else
    printf "TLP service is active and running.\n"
  fi
}

start_tlp_service() {
  if is_systemd; then
    sudo_login
    sudo systemctl enable tlp.service
    sudo systemctl start tlp.service
    sudo systemctl mask systemd-rfkill.service
    sudo systemctl mask systemd-rfkill.socket
    printf "The tlp service is enabled and started.\n"
  elif is_sysv; then
    sudo tlp start
    printf "The tlp service is started.\n"
  else
    printf "Init system is not Systemd or SysV.\n"
    printf "Manually start the TLP service.\n"
  fi
}

util_status() {
  printf "Installed utilities:\n"
  installed thermald && printf "%12s\n" "Thermald"
  installed acpi && printf "%8s\n" "ACPI"
  installed tlp && printf "%7s\n" "TLP"
  installed tlp-rdw && printf "%11s\n" "TLP-RDW"
  installed touchpad-indicator && printf "%22s\n" "Touchpad Indicator"
}

main() {
  local lhost noOpt opt optstr
  lhost="${HOSTNAME:=-$(hostname)}"
	noOpt=1
	optstr=":hils"
	while getopts "$optstr" opt; do
		case "$opt" in
			h )
				help 0
			;;
				i )
        is_laptop || die "$lhost is not a laptop." 1
        sudo_login 2
        intro
        install_thermald
        install_acpi
        install_tlp
        install_touchpad_indicator
        util_status
      ;;
      l )
        is_laptop || die "$lhost is not a laptop." 1
        util_status
      ;;
      s )
        is_laptop || die "$lhost is not a laptop." 1
        sudo_login 2
        tlp_status
      ;;
      ? )
        printf "%s Invalid option -%s\n" "$RED_ERROR" "$OPTARG" >&2
        help 2
    esac
	  noOpt=0
  done
  [[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
  shift "$(( OPTIND - 1 ))"
  over_line "$script v$version"
  exit
}

## Execution ##

main "$@"

## Execution ##
