#!/bin/bash
#############################################################################
# Script Name  : ren-hostname
# Description  : Changes the system hostname
# Dependencies : awk, sed
# Arguments    : new hostname
# Author       : Richard B. Romig, 06 Nov 2019
# Email        : rick.romig@gmail.com
# Comments     : Changes in both /etc/hostname and /etc/hosts
#              : new hostname argument should be in double-quotes
#############################################################################
# Copyright (C) 2020, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Variables ##

readonly SCRIPT=$(basename "$0")
readonly VERSION="2.0.0"
readonly UPDATED="03 May 2020"

## Functions ##

leave()
{
  local MSG="$1"

  if [ -z "$MSG" ]; then
    echo "Existing the script."
  else
    echo "$MSG"
  fi
  exit
}

usage()
{
  echo -e "\e[1;31mUsage:\e[0m $SCRIPT <new-hostname>" >&2
  exit 1
}

## Execution ##

echo "$SCRIPT v$VERSION"
echo "(Updated: $UPDATED)"
echo "Changes the system's hostname."

if [ -z "$1" ]; then
  echo -e "\n\e[1;31mError:\e[0m No hostname passed." >&2
  usage
else
  readonly NEWHOST="$1"
  readonly OLDHOST=$HOSTNAME
  [ "$NEWHOST" == "$OLDHOST" ] && leave "Hostnames are the same, no changes made."
  sudo ls > /dev/null 2>&1
fi

echo $'\n'$"Changing the hostname from $OLDHOST to $NEWHOST ..."
# Change hostname in /etc/hostname
cp -p /etc/hostname /etc/hostname.old > /dev/null 2>&1
sudo sed -i "s/$OLDHOST/$NEWHOST/" /etc/hostname
# Change hostname in /etc/hosts
cp -p /etc/hosts /etc/hosts.old > /dev/null 2>&1
sudo sed -i "s/$OLDHOST/$NEWHOST/"

# Confirm changes

HOST1=$(cat /etc/hostname)
HOST2=$(awk '/127.0.1.1/ { print $2 }' /etc/hosts)
[ -z "$HOST2" ] && HOST2=$(grep -m2 '127.0.0.1' /etc/hosts | tail -n1 | awk '{print $2}')
echo -e "/etc/hostname = $HOST1\t/etc/hosts = $HOST2"
if [ "$HOST1" == "$NEWHOST" ] && [ "$HOST2" == "$NEWHOST" ]; then
  rm /etc/hosts.old > /dev/null 2>&1
  rm /etc/hostname.old > /dev/null 2>&1
  echo "Hostname successfully changed."
  leave "Reboot required for changes to take effect."
else
  sudo mv /etc/hostname.old /etc/hostname > /dev/null 2>&1
  sudo mv /etc/hosts.old /etc/hosts > /dev/null 2>&1
  leave "Hostname change was unsuccessful. Reverted to the original hostname."
fi
