#!/bin/bash
#############################################################################
# Script Name  : rename-host
# Description  : Changes the system hostname
# Dependencies : awk, sed
# Arguments    : None
# Author       : Richard B. Romig, 06 Nov 2019
# Email        : rick.romig@gmail.com
# Comments     : Hostname is changed in both /etc/hostname and /etc/hosts.
# Hostname length limited to 15 characters for NETBIOS compatibility.
#############################################################################
# Copyright (C) 2020, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Variables ##

readonly SCRIPT=$(basename "$0")
readonly VERSION="2.1.1"
readonly UPDATED="04 Jul 2020"
readonly OLDHOST=$HOSTNAME

## Functions ##

leave()
{
  local MSG="$1"

  if [ -z "$MSG" ]; then
    echo "Existing the script."
  else
    echo "$MSG"
  fi
  exit
}

name_rules()
{
  echo $'\n'$"The new hostname should be between 5 and 15 characters."
  echo "Allowed characters: a-z, 0-9, and - (will be converted to lowercase)"
  echo "The first character cannot be a hyphen (-) or a digit."
  echo "The hostname cannot end with a hyphen (-)."
  echo "The new hostname cannot be identical to the old one (after lowercase conversion)."
}

## Execution ##

# Enter new hostname and check rules

while true
do
  clear
  echo "$SCRIPT v$VERSION (Updated: $UPDATED)"
  echo "Renames the system hostname."
  name_rules
  echo -e "\nCurrent hostname is $OLDHOST\n"

  read -rp "Enter new hostname: " NEWHOST
  STRLEN=${#NEWHOST}
  if [ "$STRLEN" -lt 2 ] || [ "$STRLEN" -gt 15 ]; then
    echo $'\n'$"Invalid length" >&2
    name_rules
    continue
  fi
  case $NEWHOST in
    -* )
      echo $'\n'$"Cannot start with a hypen" >&2
      name_rules
      continue
      ;;
    *- )
      echo $'\n'$"Cannot end with a hyphen" >&2
      name_rules
      continue ;;
    [0-9]* )
      echo $'\n'$"Cannot start with a digit" >&2
      name_rules;
      continue
      ;;
    *[^a-zA-Z0-9-]* )
      echo $'\n'$"Cannot contain special characters" >&2
      name_rules;
      continue
      ;;
    * )
      ;;
  esac
  NEWHOST=$(echo "$NEWHOST" | awk '{print tolower($0)}')
  if [ "$NEWHOST" == "$OLDHOST" ]; then
    echo "Hostnames are the same." >&2
    name_rules
    continue
  else
    break
  fi
done

# Make backups of old files and change hostnames

sudo ls > /dev/null 2>&1
echo $'\n'$"Changing the hostname from $OLDHOST to $NEWHOST ..."
cp -p /etc/hostname /etc/hostname.old > /dev/null 2>&1
cp -p /etc/hosts /etc/hosts.old > /dev/null 2>&1
sudo sed -i "s/$OLDHOST/$NEWHOST/" /etc/hostname
sudo sed -i "s/$OLDHOST/$NEWHOST/" /etc/hosts

# Confirm changes

HOST1=$(cat /etc/hostname)
HOST2=$(awk '/127.0.1.1/ { print $2 }' /etc/hosts)
[ -z "$HOST2" ] && HOST2=$(grep -m2 '127.0.0.1' /etc/hosts | tail -n1 | awk '{print $2}')
echo -e "/etc/hostname = $HOST1\t/etc/hosts = $HOST2"
if [ "$HOST1" == "$NEWHOST" ] && [ "$HOST2" == "$NEWHOST" ]; then
  rm /etc/hosts.old > /dev/null 2>&1
  rm /etc/hostname.old > /dev/null 2>&1
  echo "Hostname successfully changed."
  leave "Reboot required for changes to take effect."
else
  sudo mv /etc/hostname.old /etc/hostname > /dev/null 2>&1
  sudo mv /etc/hosts.old /etc/hosts > /dev/null 2>&1
  leave "Hostname change was unsuccessful. Reverted to the original hostname."
fi
