#!/bin/bash
#####################################################################
#Script Name  :renspace
#Description  :replaces spaces with underscores in filenames in
#              the current directory
#Dependencies :rename, egrep
#Args         :None
#Author       :Richard Romig
#Email        :rick.romig@gmail.com
#Comment      :
#####################################################################
# renspace -
# Copyright (C) 2018  Richard Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
#####################################################################

echo "Renspace - renames filenames containing spaces."
echo "Copyright 2018, Richard Romig"

# check for filenames containing spaces

if find . -maxdepth 1 -type f | grep " " >/dev/null
then
  rename -v 's/ /_/g' ./*
else
  echo "No filenames containing spaces found."
fi

exit
