#!/bin/bash
#####################################################################
# Script Name  : rmtilde
# Description  : Remove backup files with trailing ~ (tilde)
# Dependencies : find, rm
# Arguments    : None
# Author       : Richard Romig
# Email        : rick.romig@gmail.com
# Comment      :
#####################################################################
# Copyright (C) 2018  Richard Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
#####################################################################

echo "rmtilde -- removes '~' backup files."

nbu=$(find . -maxdepth 1 -type f -name \*~  | wc -l)

if [ "$nbu" -eq "0" ]; then
  echo "No files ending with '~' found."
else
  echo "Removing $nbu '~' backup files in the current directory..."
  find ./ -maxdepth 1 -type f -iname \*~ -print -exec rm {} \;
fi

exit
