#!/bin/bash
#############################################################################
# Script Name  : set-resume-var
# Description  : Set the RESUME variable after update-initramfs error
# Dependencies : awk, blkid, update-initramfs
# Arguments    : None
# Author       : Richard B. Romig, 12 Nov 2019
# Email        : rick.romig@gmail.com
# Comments     : Extacts swap partition UUID from output of /sbin/blkid
#############################################################################

# Copyright (C) 2020, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Functions ##

antix_mx()
{
  DIST_ID=$(grep 'DISTRIB_ID' /etc/lsb-release 2> /dev/null | cut -d '=' -f2)
  case $DIST_ID in
    antiX|MX ) return 0 ;;
    * ) return 1 ;;
  esac
}

## Variables ##

SCRIPT=$(basename "$0")
VERSION="1.1.3"
UPDATED="14 Sep 2020"

## Functions ##

print_message() {
  cat <<- EOF
  Set RESUME environment variable after an update-initramfs error message.
  The error message wil be similar to:
  I: The initramfs will attempt to resume from /dev/sda2
  I: (UUID=09e25397-4a2c-4fb0-a605-a7013eecb59c)
  I: Set the RESUME variable to override this.
  EOF
}

## Execution ##

sudo ls > /dev/null 2>&1

echo -e "$SCRIPT v$VERSION (Updated: $UPDATED)\n"
print_message

# Extract swap partition UUID from blkid (Artix & Ubuntu require sudo)

echo $'\n'$"Extracting the swap partition UUID using /sbin/blkid ..."
if antix_mx; then
  SWAP_UUID=$(sudo /sbin/blkid | awk '/TYPE="swap"/ {print $3}' | sed 's/"//g')
else
  SWAP_UUID=$(sudo /sbin/blkid | awk '/TYPE="swap"/ {print $2}' | sed 's/"//g')
  if [ "$SWAP_UUID" = "LABEL=swap" ]; then
    SWAP_UUID=$(sudo /sbin/blkid | awk '/TYPE="swap"/ {print $3}' | sed 's/"//g')
  fi
fi

[ -z "$SWAP_UUID" ] && (echo "No UUID for swap found."; exit)

# Set RESUME environment variable

echo $'\n'$"Setting the RESUME environment variable..."
echo "RESUME=$SWAP_UUID" | sudo tee /etc/initramfs-tools/conf.d/resume
echo "Confirmation (resume):"
echo "Contents of /etc/initramfs-tools/conf.d/resume"
/bin/cat /etc/initramfs-tools/conf.d/resume

# Update initramfs and reboot the system

echo $'\n'$"Updating initramfs ..."
sudo update-initramfs -u -k all

exit
