#!/usr/bin/env bash
#####################################################################
# Script Name  : show-cron
# Description  : Shows when anacron jobs were last run and displays
#              : crontabs for all normal and root users.
# Dependencies : anacron
# Arguments    : None
# Author       : Copyright (C) 2018, Richard Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 06 Mar 2018
# Updated      : 13 Feb 2025
# Comments     : Requires sudo privileges
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
#####################################################################

# Copyright © 2018, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

anacron_jobs() {
  local count cron_dir interval
  interval="$1"
  cron_dir="/etc/cron.$interval"
  count=$(find "$cron_dir" -maxdepth 1 -type f -iname \* | wc -l)
  [[ "$count" -gt 0 ]] && return "$TRUE" || return "$FALSE"
}

print_anacron_jobs() {
  local cron_dir interval
  interval="$1"
  cron_dir="/etc/cron.$interval"
  find "$cron_dir" -maxdepth 1 -type f -iname \* | awk -F"/" '{print "  " $NF}'
}

list_anacron_jobs() {
  local interval cron_spool
  interval="$1"
  cron_spool="/var/spool/anacron/cron.$interval"
  printf "\n%sAnacron %s:%s Last run on %s\n" "$orange" "${interval^}" "$normal" "$(sudo cat "$cron_spool" 2>/dev/null)"
  if anacron_jobs "$interval"; then
    print_anacron_jobs "$interval"
  else
    printf "No jobs scheduled.\n"
  fi
}

show_anacron() {
  local interval intervals
  intervals=( daily weekly monthly )
  for interval in "${intervals[@]}"; do
    list_anacron_jobs "$interval"
  done
}

show_user_cron() {
	local index max norm_user num_users
  num_users=$(awk -F: '$3 >= 1000 && !($1 == "nobody" && $3 == 65534) {SUM+=1} END {print SUM}' /etc/passwd)
  index=1000  # starting point for regular users
  max=$(( num_users + index ))

  while [[ "$index" -le "$max" ]]; do
    norm_user="$(awk -v pat="$index" -F: '$0~pat{print $1}' /etc/passwd)"
    if [[ -n "$norm_user" ]]; then
      printf "\n%sCron jobs for %s:%s\n" "$orange" "${norm_user^}"  "$normal"
      sudo crontab -l -u "$norm_user" | grep -v '^#' | awk '{print "  "$1,$2,$3,$4,$5"\t"$6}'
		fi
    (( index++ ))
  done
}

show_root_cron() {
  printf "\n%sCron jobs for root:%s\n" "$orange" "$normal"
  sudo crontab -l | grep -v '^#' | awk '{print "  "$1,$2,$3,$4,$5"\t"$6}'
}

main() {
  local script version lhost interval intervals
  script=$(basename "$0")
  version="6.2.25044"
  lhost="${HOSTNAME:-$(hostname)}"

  sudo_login 0
  clear
  printf "%s%sJobs for %s%s\n" "$bold" "$green" "$lhost" "$normal"
  show_anacron
  show_user_cron
  show_root_cron
  over_line "$script v$version" "-"
  exit
}

## Execution ##

main "$@"
