#!/usr/bin/env bash
#####################################################################
# Script Name  : show-cron
# Description  : Shows when anacron jobs were last run and displays
#              : crontabs for all normal and root users.
# Dependencies : None
# Arguments    : None
# Author       : Copyright (C) 2018, Richard Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 06 Mar 2018
# Updated      : 27 Sep 2024
# Comments     : Requires sudo privileges
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0
#####################################################################

# Copyright © 2018, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

jobs() {
  local count cron_d interval
  interval="$1"
  cron_d="/etc/cron"
  count=$(find "$cron_d.$interval" -maxdepth 1 -type f -iname \* | wc -l)
  [[ "$count" -gt 0 ]] && return "$TRUE" || return "$FALSE"
}

show_daily_jobs() {
  local daily="/var/spool/anacron/cron.daily"
  printf "\n%sAnacron Daily:%s Last run on %s\n" "$orange" "$normal" "$(sudo cat "$daily" 2>/dev/null)"
  if jobs "daily"; then
    find /etc/cron.daily -maxdepth 1 -type f -iname \* | awk -F"/" '{print "  " $NF}'
  else
    printf "No jobs scheduled.\n"
  fi
}

show_weekly_jobs() {
  local weekly="/var/spool/anacron/cron.weekly"
  printf "\n%sAnacron Weekly:%s Last run on %s\n" "$orange" "$normal" "$(sudo cat "$weekly" 2>/dev/null)"
  if jobs "weekly"; then
    find /etc/cron.weekly -maxdepth 1 -type f -iname \* | awk -F"/" '{print "  " $NF}'
  else
    printf "No jobs scheduled.\n"
  fi
}

show_monthly_jobs() {
  local monthly="/var/spool/anacron/cron.monthly"
  printf "\n%sAnacron Monthly:%s Last run on %s\n" "$orange" "$normal" "$(sudo cat "$monthly" 2>/dev/null)"
  if jobs "monthly"; then
    find /etc/cron.monthly -maxdepth 1 -type f -iname \* | awk -F"/" '{print "  " $NF}'
  else
    printf "No jobs scheduled.\n"
  fi
}

show_user_cron() {
	local index max num_users
  num_users=$(awk -F: '$3 >= 1000 && !($1 == "nobody" && $3 == 65534) {SUM+=1} END {print SUM}' /etc/passwd)
  index=1000
  max=$(( num_users + index ))

  while [[ "$index" -le "$max" ]]; do
    norm_user="$(awk -v pat="$index" -F: '$0~pat{print $1}' /etc/passwd)"
    if [[ -n "$norm_user" ]]; then
      printf "\n%sCron jobs for %s:%s\n" "$orange" "${norm_user^}"  "$normal"
      sudo crontab -l -u "$norm_user" | grep -v '^#' | sed 's/>\/dev\/null 2>&1//' | awk -F"/" '{print "  "$1"\t"$NF}'
		fi
    (( index++ ))
  done
}

show_root_cron() {
  printf "\n%sCron jobs for root:%s\n" "$orange" "$normal"
  sudo crontab -l | grep -v '^#' | sed 's/>\/dev\/null 2>&1//' | awk -F"/" '{print "  "$1"\t"$NF}'
  printf "\n"
}

main() {
	local lhost _script _version
  _script; _script=$(basename "$0")
  _version="5.5.24271"
  lhost="${HOSTNAME:-$(hostname)}"

  sudo_login 0
  clear
  printf "%s%sJobs for %s%s\n" "$bold" "$green" "$lhost" "$normal"
  show_daily_jobs
  show_weekly_jobs
  show_monthly_jobs
  show_user_cron
  show_root_cron
  under_line "$_script v$_version" "-"
  exit
}

## Execution ##

main
