#!/bin/bash
#####################################################################
# Script Name  : sysinfo
# Description  : Gathers system information to a file in home directory
# Dependencies : dmidecode, awk, grep, hdpram, lsblk
# Args         : None
# Author       : Richard Romig
# Email        : rick.romig@gmail.com
# Comment      : Requires root/sudo privileges
# dmidecode may produce error messages in some systems. They can be
# safely ignored and removed from file with any text editor.
#####################################################################
# Copyright (C) 2018  Richard Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
####################################################################

# Base variables

myuser=$USER
myhost=$HOSTNAME
infofile="/home/$myuser/$myhost.info"
today=$(date +"%d %B %Y")
version="v 2.0.3"

# Computer information

mfgname=$(sudo /usr/sbin/dmidecode -s system-manufacturer 2>/dev/null)
prodname=$(sudo /usr/sbin/dmidecode -s system-product-name 2>/dev/null)
vername=$(sudo /usr/sbin/dmidecode -s system-version 2>/dev/null)
sernum=$(sudo /usr/sbin/dmidecode -s system-serial-number 2>/dev/null)

# RAM and CPU

physmem=$(awk '/MemTotal/ {print $2}' /proc/meminfo | \
  xargs -I {} echo "scale=4; {}/1024^2" | bc)
cpuinfo=$(/usr/bin/lscpu \
  | awk '/Model name/ {print $3" "$4" "$5" " $6" "$7" "$8" "$9}')

# Network

ethint=$(nmcli dev | awk '/ethernet/ {print $1}')
wifint=$(nmcli dev | awk '/wifi/ {print $1}')
ethernet=$(/usr/bin/lspci | grep 'Ethernet controller' | cut -c 30-)
wireless=$(/usr/bin/lspci | grep 'Network controller' | cut -c 29-)

# Battery

battery=$(/usr/bin/upower -i `/usr/bin/upower -e | grep 'BAT'` \
  | awk '/native-path/ {print $2}')

# Write data to file in user's home directory

clear
echo "SysInfo ($version), Copyright 2019, Richard Romig" > "$infofile"
{
  echo -e "System information for $myhost as of $today:\n"
  echo -e "Manufacturer:\t$mfgname"
  echo -e "Product name:\t$prodname"
  echo -e "Version:\t$vername"
  echo -e "Serial number:\t$sernum\n"
  echo -e "Operating System: $(/usr/bin/lsb_release -d | cut -c 14-)\n"
  echo -e "CPU:\t$cpuinfo"
  echo -e "RAM:\t$physmem GB"
  echo "Graphics Adapter: "
  echo -e "\t$(/usr/bin/lspci | grep 'VGA' | cut -c 36-)"
  echo "Network Adapter:"
  if [ -n "$ethernet" ]; then
    echo -e "\tEthernet: $ethint = $ethernet"
    read -r ethadd < "/sys/class/net/$ethint/address"
    echo -e "\tMAC addr: $ethadd"
  fi
  if [ -n "$wireless" ]; then
    echo -e "\tWireless: $wifint = $wireless"
    read -r wifiadd < "/sys/class/net/$wifint/address"
    echo -e "\tMAC addr: $wifiadd"
  fi
  echo -e "\nHard Disk information:"
  for Disk in /dev/sd[a-z]
  do
    hddev=$(sudo /sbin/hdparm -I "${Disk}" | grep -e '/dev/')
    hdmodel=$(sudo /sbin/hdparm -I "${Disk}" | awk '/Model Number/ {print $3" "$4}')
    hdserial=$(sudo /sbin/hdparm -I "${Disk}" | awk '/Serial Number/ {print $3}')
    hdsize=$(sudo /sbin/hdparm -I "${Disk}" | awk '/GB/ {print $7" "$8" "$9" "$10}')

    echo "$hddev"
    echo -e "\tModel Number : $hdmodel"
    echo -e "\tSerial Number: $hdserial"
    echo -e "\tCapacity: $hdsize\n"
  done
  echo "Partition information:"
  /bin/lsblk -o NAME,SIZE,TYPE,MOUNTPOINT
  [ -n "$battery" ] && echo -e "\nBattery:\t$battery"
} >> "$infofile"

# Display the file to the screen

cat "$infofile"

exit
