#!/bin/bash
#####################################################################
# Script Name  : sysinfo
# Description  : Gathers system information to a file in home directory
# Dependencies : awk, dmidecode, grep, hdpram, lsblk, tee
# Args         : None
# Author       : Richard Romig
# Email        : rick.romig@gmail.com
# Comment      : Requires root/sudo privileges
# dmidecode may produce error messages in some systems. They can be
# safely ignored and removed from the file with any text editor.
#####################################################################
# Copyright (C) 2018  Richard Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
####################################################################

sudo ls > /dev/null 2>&1

# hdparm needed to get hard drive information

dpkg -l | grep -qw hdparm || sudo apt install -yyq hdparm

# Base variables

MYUSER=$USER
MYHOST=$HOSTNAME
INFOFILE="/home/$MYUSER/$MYHOST.info"
TODAY=$(date +"%d %B %Y")
VERSION="v 2.0.5"

# Computer information

MFGNAME=$(sudo /usr/sbin/dmidecode -s system-manufacturer 2>/dev/null)
PRODNAME=$(sudo /usr/sbin/dmidecode -s system-product-name 2>/dev/null)
VERNAME=$(sudo /usr/sbin/dmidecode -s system-version 2>/dev/null)
SERNUM=$(sudo /usr/sbin/dmidecode -s system-serial-number 2>/dev/null)

# CPU and RAM

CPUINFO=$(/usr/bin/lscpu \
  | awk '/Model name/ {print $3" "$4" "$5" " $6" "$7" "$8" "$9}')
PHYSMEM=$(awk '/MemTotal/ {print $2}' /proc/meminfo | \
  xargs -I {} echo "scale=4; {}/1024^2" | bc)

# Network

ETHINT=$(nmcli dev | awk '/ethernet/ {print $1}')
WIFIINT=$(nmcli dev | awk '/wifi/ {print $1}')
ETHERNETDEV=$(/usr/bin/lspci | grep 'Ethernet controller' | cut -c 30-)
WIRELESSDEV=$(/usr/bin/lspci | grep 'Network controller' | cut -c 29-)

# Battery

BATTERY=$(/usr/bin/upower -i "$(/usr/bin/upower -e | grep 'BAT')" \
  | awk '/native-path/ {print $2}')

# Write data to file in user's home directory

clear
{
  echo "SysInfo ($VERSION), Copyright 2019, Richard Romig"
  echo -e "System information for $MYHOST as of $TODAY:\n"
  echo -e "Manufacturer:\t$MFGNAME"
  echo -e "Product name:\t$PRODNAME"
  echo -e "Version:\t$VERNAME"
  echo -e "Serial number:\t$SERNUM\n"
  echo -e "Operating System: $(/usr/bin/lsb_release -d | cut -c 14-)\n"
  echo -e "CPU:\t$CPUINFO"
  echo -e "RAM:\t$PHYSMEM GB"
  echo "Graphics Adapter: "
  echo -e "\t$(/usr/bin/lspci | grep 'VGA' | cut -c 36-)"
  echo "Network Adapter:"
  if [ -n "$ETHERNETDEV" ]; then
    echo -e "\tEthernet: $ETHINT = $ETHERNETDEV"
    read -r ETHADDR < "/sys/class/net/$ETHINT/address"
    echo -e "\tMAC addr: $ETHADDR"
  fi
  if [ -n "$WIRELESSDEV" ]; then
    echo -e "\tWireless: $WIFIINT = $WIRELESSDEV"
    read -r WIFIADDR < "/sys/class/net/$WIFIINT/address"
    echo -e "\tMAC addr: $WIFIADDR"
  fi
  echo -e "\nHard Disk information:"
  for DISK in /dev/sd[a-z]
  do
    HDDEV=$(sudo /sbin/hdparm -I "${DISK}" | grep -e '/dev/')
    HDMODEL=$(sudo /sbin/hdparm -I "${DISK}" | awk '/Model Number/ {print $3" "$4}')
    HDSERIAL=$(sudo /sbin/hdparm -I "${DISK}" | awk '/Serial Number/ {print $3}')
    HDSIZE=$(sudo /sbin/hdparm -I "${DISK}" | awk '/GB/ {print $7" "$8" "$9" "$10}')
    echo "$HDDEV"
    echo -e "\tModel Number : $HDMODEL"
    echo -e "\tSerial Number: $HDSERIAL"
    echo -e "\tCapacity: $HDSIZE"
  done
  echo $'\n'$"Partition information:"
  /bin/lsblk -o NAME,SIZE,TYPE,MOUNTPOINT
  [ -n "$BATTERY" ] && echo -e "\nBattery:\t$BATTERY"
} | tee "$INFOFILE"

exit
