#!/usr/bin/env bash
#####################################################################
#!/usr/bin/env bash
# Description  : Displays a snapshot of system resources
# Dependencies : jq, lm-sensors, sensors
# Arguments    : none
# Author       : Copyright (C) 2018,Richard Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 17 Nov 2018
# Updated      : 08 Nov 2024
# Comments     : Inspired by Joe Collins <https://www.ezeeLinux.com>
#              : and Luke Smith <https://lukesmith.xyz>
# 13 Feb 2022  : Added `-x fuse.portal` to df command to eliminate this error:
#              : df: /run/user/1000/doc: Operation not permitted
# License      : GNU General Public License, version 2.0
#####################################################################

# Copyright © 2018, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Functions ##

check_drivetemp() {
  sensors | grep -qw drivetemp || sudo modprobe drivetemp
  grep -qw drivetemp /etc/modules || echo drivetemp | sudo tee -a /etc/modules
  printf "drivetemp module - OK\n"
  sleep 2
}

check_dependencies() {
  local packages=( jq lm-sensors )
  check_packages "${packages[@]}"
  # Check drivetemp modules for SATA drives.
  [[ -b /dev/sda ]] && check_drivetemp
}

nvme_temperature() {
	local drive drv_name sensor_json
  sensor_json="$1"
	for drive in /dev/nvme0n[0-9]; do
		drv_name=$(echo -n "$drive" | awk -F/ '{print $NF}')
		if echo "$sensor_json" | grep -q 'nvme-pci-0300'; then
			printf "%-10s%2.1f\U2103 \n" "$drv_name:" "$(echo "$sensor_json" | jq -r '."nvme-pci-0300"."Composite"."temp1_input"')"
    else
      printf "%-10sNot available\n" "$drv_name:"
		fi
	done
}

sata_temperature() {
	local drive drv_name sensor_json
  sensor_json="$1"
	for drive in /dev/sd[a-z]; do
		drv_name=$(echo -n "$drive" | awk -F/ '{print $NF}')
		if echo "$sensor_json" | grep -q 'drivetemp-scsi-0-0'; then
			printf "%-10s%2.1f\U2103 \n" "$drv_name:" "$(echo "$sensor_json" | jq -r '."drivetemp-scsi-0-0"."temp1"."temp1_input"')"
		elif echo "$sensor_json" | grep -q 'drivetemp-scsi-1-0'; then
			printf "%-10s%2.1f\U2103 \n" "$drv_name:" "$(echo "$sensor_json" | jq -r '."drivetemp-scsi-1-0"."temp1"."temp1_input"')"
		elif echo "$sensor_json" | grep -q 'drivetemp-scsi-2-0'; then
			printf "%-10s%2.1f\U2103 \n" "$drv_name:" "$(echo "$sensor_json" | jq -r '."drivetemp-scsi-2-0"."temp1"."temp1_input"')"
    else
      printf "%-10sNot available\n" "$drv_name:"
		fi
	done
}

cpu_temperature(){
  local sensor_json="$1"
	if echo "$sensor_json" | grep -q 'k10temp-pci-00c3'; then
		printf "%-10s%2.1f\U2103 \n" "CPU:" "$(echo "$sensor_json" | jq -r '."k10temp-pci-00c3"."temp1"."temp1_input"')"
	elif echo "$sensor_json" | grep -q 'dell_smm-virtual-0'; then
		printf "%-10s%2.1f\U2103 \n" "CPU:" "$(echo "$sensor_json" | jq -r '."dell_smm-virtual-0"."CPU"."temp1_input"')"
	elif echo "$sensor_json" | grep -q 'Package id 0'; then
		printf "%-10s%2.1f\U2103 \n" "CPU:" "$(echo "$sensor_json" | jq -r '."coretemp-isa-0000"."Package id 0"."temp1_input"')"
	elif echo "$sensor_json" | grep -q 'Core 0'; then
		printf "%-10s%2.1f\U2103 \n" "CPU:" "$(echo "$sensor_json" | jq -r '."coretemp-isa-0000"."Core 0"."temp2_input"')"
  else
    printf "%-10sNot available\n" "CPU:"
	fi
}

gpu_temperature() {
  # Not all systems will display GPU temperature.
  local sensor_json="$1"
  if echo "$sensor_json" | grep -q 'nouveau-pci-0100'; then
    printf "%-10s%2.1f\U2103 \n" "GPU:" "$(echo "$sensor_json" | jq -r '."nouveau-pci-0100"."temp1"."temp1_input"')"
  elif echo "$sensor_json" | grep -q 'pch_skylake-virtual-0'; then
    printf "%-10s%2.1f\U2103 \n" "GPU:" "$(echo "$sensor_json" | jq -r '."pch_skylake-virtual-0"."temp1"."temp1_input"')"
  else
    printf "%-10sNot available\n" "GPU:"
  fi
}

memory_usage() {
	printf "\n%sMemory usage:%s %s\n" "$orange" "$normal" "$(/usr/bin/free -h | awk '/^Mem:/ {print $3 "/" $2}' | sed 's/i//g')"
  printf "%sProcess%s\t\t%sPercentage%s\n" "$underline" "$normal" "$underline" "$normal"
  ps axch -o cmd:15,%mem --sort=-%mem | head -n 5
}

cpu_usage() {
  local cores cpu_usage cpu_use
  cores="$(grep -c "^processor" /proc/cpuinfo)"
  cpu_usage="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
  cpu_use="$((${cpu_usage/\.*} / ${cores:-1}))"
	printf "\n%sCPU usage: %s%s%%\n" "$orange" "$normal" "$cpu_use"
  printf "%sProcess%s\t\t%sPercentage%s\n" "$underline" "$normal" "$underline" "$normal"
  ps axch -o cmd:15,%cpu --sort=-%cpu | head -n 5
}

disk_usage() {
	printf "\n%sDisk usage:%s\n" "$orange" "$normal"
  df -hT -x fuse.portal | sed -n '1p;/^\//p'  # '-x fuse.portal' to eliminate 'df: /run/user/1000/doc: Operation not permitted' error
}

show_header() {
  local local_host="${HOSTNAME:-$(hostname)}"
  printf "%s%sSystem Status%s\n" "$bold" "$lightyellow" "$normal"
  printf "%s%-16s%s\n" "$orange" "Computer name:" "$local_host"
  printf "%-16s%s\n" "Distribution:" "$(get_distribution)"
  printf "%-16s%s%s\n" "Kernel version:" "$(uname -sr)" "$normal"
}

show_footer() {
  local script version
  script=$(basename "$0")
  version="6.5.24313"
  printf "\nThe system has been %s\n" "$(/usr/bin/uptime -p)"
  printf "Last reboot: %s\n" "$(/usr/bin/who -b | awk '{print $(NF-1)" at "$NF}')"
  over_line "$script $version"
  exit
}

main() {
  check_dependencies
  local sensor_json script version
  script=$(basename "$0")
  version="6.5.24313"
  sensor_json="$(sensors -j)"
  clear
  show_header
  memory_usage
  cpu_usage
	printf "\n%sTemperatures:%s\n"  "$orange" "$normal"
  cpu_temperature "$sensor_json"
  gpu_temperature "$sensor_json"
  [[ -c /dev/nvme0 ]] && nvme_temperature "$sensor_json"
  [[ -b /dev/sda ]] && sata_temperature "$sensor_json"
  disk_usage
  show_footer
}

## Execution ##

main "$@"
