#!/bin/bash
###############################################################################
#Script Name  :upper2lower#
#Description  :Renames uppercase filenames to lowercase
#Dependencies :rename
#Args         :filename to be renamed
#Author       :Richard Romig
#Email        :rick.romig@gmail.com
#Comment      :If no filename is passed, renames all files in folder
#             :to all lowercase
###############################################################################
# Copyright (C) 2018  Richard Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
###############################################################################

usage () {
  echo "Usage: $SCRIPT [filename]"
  echo -e "\e[1;31mWARNING!\3[0m] If no filename is passed, $SCRIPT will change ALL filenames in the current directory to lowercase."
}

SCRIPT=$(basename "$0")
FILE=$1
VERSION="2.0.2"
UPDATED="01 Sep 2019"

echo "$SCRIPT v$VERSION (Updated: $UPDATED)"
echo "Changes uppercase letters in files names to lowercase."
echo "Copyright 2018, Richard Romig"

# if no filename passed then get confirmation from user
if  [ -z "$FILE"  ]; then
  usage
  read -rn1 -p "Are you sure you want to do this? [y/N] " YN
  case $YN in
    [Yy]* )
      rename -v 'y/A-Z/a-z/' ./*
      ;;
    * )
      usage
      exit
      ;;
  esac
elif [ -e "$MYFILE" ]; then
  rename -v 'y/A-Z/a-z/' "$FILE"
else
  echo -e "\e[41mERROR: $FILE does not exist. Try again.\e[0m" >&2
  usage
  exit 1
fi

exit

