#!/usr/bin/env bash
##########################################################################
# Script Name  : verify-iso
# Description  : Verifies SHA256, SHA512, and MD5 checksums of ISO files
# Dependencies : fzf
# Arguments    : see help function
# Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Crated       : 09 Apr 2022
# Updated      : 20 Jan 2025
# Comments     : Each ISO file must have its own checksum file.
#              : Checksum file must be one line only for ISO being checked.
#              : Checksum files must have one of the following extensions:
#              : .md5, .sha256, or .sha512
# TODO (Rick)  :
#
# Copyright © 2022, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
# License      : GNU General Public License, version 2.0
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

script=$(basename "$0"); readonly script
readonly version="9.6.25020"

## Functions ##

help() {
	local errcode updated
	errcode="${1:-2}"
	updated="20 Jan 2025"
	cat << _HELP_
${orange}$script${normal} $version, Updated: $updated
Verifies SHA256/SHA512/MD5 checksums with ISO files.

${green}Usage:${normal} $script [OPTION]

${orange}Available options:${normal}
  -h  Display help
  -v  Verify ISO with checksum

  * With no argument, defaults to verifying an ISO file.
	* Checksum files must be a single line specifically for the ISO file you wish to check.
  * Checksum files must have a file extension of .md5, .sha1, .sha256. or .sha512.
  * The basename of the checksum file should match the basename name of the ISO.

_HELP_
  exit "$errcode"
}

select_iso() {
	local iso_d isofile
	iso_d="$1"
	isofile=$(find "$iso_d" -maxdepth 3 -type f -iname "*.iso" -print | sort -d | fzf --height 75% --reverse --prompt "Select the ISO file to check: ")
	echo "$isofile"
}

select_checksum() {
	local iso_d checksum
	iso_d="$1"
	checksum=$(find "$iso_d" -maxdepth 3 -type f -name "*.md5" -or -name "*.sha*" | sed 's/\.\///' | sort -d | fzf --height 75% --reverse --prompt "Select the checksum file: ")
	echo "$checksum"
}

check_sha1() {
	local iso_sha src_sha iso_file sha_file
	iso_file="$1"
	sha_file="$2"
  dots "."
	iso_sha=$(/usr/bin/sha1sum "$iso_file" | awk '{print $1}')
	src_sha=$(awk '{print $1}' "$sha_file")
  kill "$!"; tput cnorm
  printf "done\n\nSelected ISO: %s\n" "$(basename "$iso_file")"
	printf "ISO checksum: %s\n" "$iso_sha"
	printf "SHA checksum: %s\n" "$src_sha"
	[[ "$iso_sha" == "$src_sha" ]] && return "$TRUE" || return "$FALSE"
}

check_sha256() {
	local iso_sha src_sha iso_file sha_file
	iso_file="$1"
	sha_file="$2"
  dots "."
	iso_sha=$(/usr/bin/sha256sum "$iso_file" | awk '{print $1}')
	src_sha=$(awk '{print $1}' "$sha_file")
  kill "$!"; tput cnorm
  printf "done\n\nSelected ISO: %s\n" "$(basename "$iso_file")"
	printf "ISO checksum: %s\n" "$iso_sha"
	printf "SHA checksum: %s\n" "$src_sha"
	[[ "$iso_sha" == "$src_sha" ]] && return "$TRUE" || return "$FALSE"
}

check_sha512() {
	local iso_sha src_sha iso_file sha_file
  iso_file="$1"
	sha_file="$2"
  dots "."
	iso_sha=$(/usr/bin/sha512sum "$iso_file" | awk '{print $1}')
	src_sha=$(awk '{print $1}' "$sha_file")
  kill "$!"; tput cnorm
  printf "done\n\nSelected ISO: %s\n" "$(basename "$iso_file")"
	printf "ISO checksum: %s\n" "$iso_sha"
	printf "SHA checksum: %s\n" "$src_sha"
	[[ "$iso_sha" == "$src_sha" ]] && return "$TRUE" || return "$FALSE"
}

check_md5() {
	local iso_md5 md5_file src_md5 iso_file
  iso_file="$1"
  md5_file="$2"
  dots "."
  iso_md5=$(/usr/bin/md5sum "$iso_file" | awk '{print $1}')
  src_md5=$(awk '{print $1}' "$md5_file")
  kill "$!"; tput cnorm
  printf "done\n\nSelected ISO: %s\n" "$(basename "$iso_file")"
  printf "ISO checksum: %s\n" "$iso_md5"
  printf "MD5 checksum: %s\n" "$src_md5"
  [[ "$iso_md5" == "$src_md5" ]] && return "$TRUE" || return "$FALSE"
}

status_msg() {
  local status="${1:-0}"
  if [[ "$status" -eq 0 ]]; then
		printf "%sThe checksums match.%s\n" "$green" "$normal"
  else
		printf "%sThe checksums do not match.%s\n" "$lightred" "$normal"
		printf "Verify checksum with the ISO download site.\n"
  fi
}

check_checksum() {
	local file lines
  file="$1"
  lines=$(wc -l "$file" | cut -d' ' -f1)
  [[ "$lines" -eq 1 ]] && return "$TRUE" || return "$FALSE"
}

compare_checksums() {
	local ext checksum iso
	iso="$1"
	checksum="$2"
	ext="${checksum##*.}"
	printf "Comparing checksums."
	case "$ext" in
	  "md5" )
	    check_md5 "$iso" "$checksum"
	    status_msg "$?"
	  ;;
	  "sha1" )
	    check_sha1 "$iso" "$checksum"
	    status_msg "$?"
	  ;;
	  "sha256" )
	    check_sha256 "$iso" "$checksum"
	    status_msg "$?"
	  ;;
	  "sha512" )
	    check_sha512 "$iso" "$checksum"
	    status_msg "$?"
	  ;;
	  * )
	    printf "\n"
	    diehard "Invalid extension" "Checksum must be one of the following:" ".md5 .sha1 .sha256 .sha512" "$script $version"
	esac
}

verify_iso() {
	local checksum isofile iso_dir
	iso_dir="$HOME/Downloads/ISO/"
	isofile=$(select_iso "$iso_dir")
	checksum=$(select_checksum "$iso_dir")
	printf "\n%-18s %s\n" "Selected ISO:" "$(basename "$isofile")"
	printf "%-18s %s\n\n" "Selected Checksum:" "$(basename "$checksum")"
	check_checksum "$checksum" || diehard "Too many lines in checksum file." "Reduce file to a single line." "$script $version"
	compare_checksums "$isofile" "$checksum"
}

check_verify() {
	check_package fzf
	printf "Verifies SHA1/SHA256/SHA512/MD5 checksums with ISO files.\n"
	verify_iso
}

main() {
	local noOpt optstr opt
	noOpt=1
	optstr=":hv"
	while getopts "$optstr" opt; do
		case "$opt" in
			h )
				help 0 ;;
			v )
				check_verify ;;
			? )
				printf "%s Invalid option: -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help 2
		esac
		noOpt=0
	done
	[[ "$noOpt" = 1 ]] && check_verify
	shift "$(( OPTIND - 1 ))"
	exit
}

## Execution ##

main "$@"
