#!/usr/bin/env bash
##########################################################################
# Script Name  : verify-iso
# Description  : Verifies SHA256, SHA512, and MD5 checksums of ISO files
# Dependencies : fzf
# Arguments    : see help function
# Author       : Copyright (C) 2022, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Crated       : 09 Apr 2022
# Updated      : 17 Mar 2025
# Comments     : Each ISO file must have its own checksum file.
#              : Checksum file must be one line only for ISO being checked.
#              : Checksum files must have one of the following extensions:
#              : .md5, sha1, .sha256, or .sha512
# TODO (Rick)  :
# License      : GNU General Public License, version 2.0 <https://github.com/RickRomig/bashscripts>
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Source function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

script=$(basename "$0"); readonly script
readonly version="10.0.25076"
FMENU="fzf --header=$(basename "$0") \
           --layout=reverse \
           --exact \
           --border=bold \
           --border=rounded \
           --margin=5% \
           --color=dark \
           --height=95% \
           --info=hidden \
           --header-first \
           --bind change:top \
           --prompt"

## Functions ##

help() {
	local errcode updated
	errcode="${1:-2}"
	updated="17 Mar 2025"
	cat << _HELP_
${orange}$script${normal} $version, Updated: $updated
Verifies SHA256/SHA512/MD5 checksums with ISO files.

${green}Usage:${normal} $script [OPTION]

${orange}Available options:${normal}
  -h  Show this help message and exit
  -v  Verify ISO with checksum

  * With no argument, defaults to verifying an ISO file.
	* Checksum files must be a single line specifically for the ISO file you wish to check.
  * Checksum files must have a file extension of .md5, .sha1, .sha256, or .sha512.
  * The basename of the checksum file should match the basename name of the ISO.

_HELP_
  exit "$errcode"
}

select_directory() {
	local iso_d selected_dir
	local iso_dirs=()
	for dist_d in $HOME/Downloads/ISO; do
		[[ -d "$dist_d" ]] && iso_dirs+=("$(find "$dist_d" -type d -print | sort -d)")
	done
	selected_dir=$($FMENU "Select distribution directory: " < <(printf "%s\n" "${iso_dirs[@]}"))
	printf "%s" "$selected_dir"
}

select_iso() {
	local iso_d selected_iso
	iso_d="$1"
	local iso_files=()
	for iso_files in $iso_d; do
		[[ -d "$iso_d" ]] && iso_files+=("$(find "$iso_d" -type f -iname "*.iso" -printf "%f\n" | sort -d)")
	done
	selected_iso=$($FMENU "Select ISO file: " < <(printf "%s\n" "${iso_files[@]}"))
	printf "%s" "$selected_iso"
}

select_checksum() {
	local iso_d selected_chksum
	iso_d="$1"
	local chksum_files=()
	for chksum_files in $iso_d; do
		[[ -d "$iso_d" ]] && chksum_files+=("$(find "$iso_d" -type f \( -name "*.md5" -or -name "*.sha*" \) -printf "%f\n" | sort -d)")
	done
	selected_chksum=$($FMENU "Select Checksum file: " < <(printf "%s\n" "${chksum_files[@]}"))
	printf "%s" "$selected_chksum"
}

check_sha1() {
	local iso_sha src_sha iso_file sha_file
	iso_file="$1"
	sha_file="$2"
  dots "."
	iso_sha=$(/usr/bin/sha1sum "$iso_file" | awk '{print $1}')
	src_sha=$(awk '{print $1}' "$sha_file")
  kill "$!"; tput cnorm
  printf "done\n\nSelected ISO: %s\n" "$(basename "$iso_file")"
	printf "ISO checksum: %s\n" "$iso_sha"
	printf "SHA checksum: %s\n" "$src_sha"
	[[ "$iso_sha" == "$src_sha" ]] && return "$TRUE" || return "$FALSE"
}

check_sha256() {
	local iso_sha src_sha iso_file sha_file
	iso_file="$1"
	sha_file="$2"
  dots "."
	iso_sha=$(/usr/bin/sha256sum "$iso_file" | awk '{print $1}')
	src_sha=$(awk '{print $1}' "$sha_file")
  kill "$!"; tput cnorm
  printf "done\n\nSelected ISO: %s\n" "$(basename "$iso_file")"
	printf "ISO checksum: %s\n" "$iso_sha"
	printf "SHA checksum: %s\n" "$src_sha"
	[[ "$iso_sha" == "$src_sha" ]] && return "$TRUE" || return "$FALSE"
}

check_sha512() {
	local iso_sha src_sha iso_file sha_file
  iso_file="$1"
	sha_file="$2"
  dots "."
	iso_sha=$(/usr/bin/sha512sum "$iso_file" | awk '{print $1}')
	src_sha=$(awk '{print $1}' "$sha_file")
  kill "$!"; tput cnorm
  printf "done\n\nSelected ISO: %s\n" "$(basename "$iso_file")"
	printf "ISO checksum: %s\n" "$iso_sha"
	printf "SHA checksum: %s\n" "$src_sha"
	[[ "$iso_sha" == "$src_sha" ]] && return "$TRUE" || return "$FALSE"
}

check_md5() {
	local iso_md5 md5_file src_md5 iso_file
  iso_file="$1"
  md5_file="$2"
  dots "."
  iso_md5=$(/usr/bin/md5sum "$iso_file" | awk '{print $1}')
  src_md5=$(awk '{print $1}' "$md5_file")
  kill "$!"; tput cnorm
  printf "done\n\nSelected ISO: %s\n" "$(basename "$iso_file")"
  printf "ISO checksum: %s\n" "$iso_md5"
  printf "MD5 checksum: %s\n" "$src_md5"
  [[ "$iso_md5" == "$src_md5" ]] && return "$TRUE" || return "$FALSE"
}

status_msg() {
  local status="${1:-0}"
  if [[ "$status" -eq 0 ]]; then
		printf "%sThe checksums match.%s\n" "$green" "$normal"
  else
		printf "%sThe checksums do not match.%s\n" "$lightred" "$normal"
		printf "Verify checksum with the ISO download site.\n"
  fi
}

check_checksum() {
	local file lines
  file="$1"
  lines=$(wc -l < "$file")
  [[ "$lines" -eq 1 ]] && return "$TRUE" || return "$FALSE"
}

compare_checksums() {
	local ext checksum iso
	iso="$1"
	checksum="$2"
	ext="${checksum##*.}"
	printf "Comparing checksums."
	case "$ext" in
	  "md5" )
	    check_md5 "$iso" "$checksum"
	    status_msg "$?"
	  ;;
	  "sha1" )
	    check_sha1 "$iso" "$checksum"
	    status_msg "$?"
	  ;;
	  "sha256" )
	    check_sha256 "$iso" "$checksum"
	    status_msg "$?"
	  ;;
	  "sha512" )
	    check_sha512 "$iso" "$checksum"
	    status_msg "$?"
	  ;;
	  * )
	    printf "\n"
	    diehard "Invalid extension" "Checksum must be one of the following:" ".md5 .sha1 .sha256 .sha512" "$script $version"
	esac
}

verify_iso() {
	local checksum isofile iso_dir
	iso_dir=$(select_directory)
	isofile=$(select_iso "$iso_dir")
	checksum=$(select_checksum "$iso_dir")
	printf "\n%-18s %s\n" "Selected Distro:" "$(basename "$iso_dir")"
	printf "%-18s %s\n" "Selected ISO:" "$isofile"
	printf "%-18s %s\n\n" "Selected Checksum:" "$checksum"
	check_checksum "$iso_dir/$checksum" || diehard "Too many lines in checksum file." "Reduce file to a single line." "$script $version"
	compare_checksums "$iso_dir/$isofile" "$iso_dir/$checksum"
}

check_verify() {
	check_package fzf
	printf "Verifies SHA1/SHA256/SHA512/MD5 checksums with ISO files.\n"
	verify_iso
}

main() {
	local noOpt optstr opt
	noOpt=1
	optstr=":hv"
	while getopts "$optstr" opt; do
		case "$opt" in
			h )
				help 0 ;;
			v )
				check_verify ;;
			? )
				printf "%s Invalid option: -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help 2
		esac
		noOpt=0
	done
	[[ "$noOpt" = 1 ]] && check_verify
	shift "$(( OPTIND - 1 ))"
	over_line "$script $version"
	exit
}

## Execution ##

main "$@"
