#!/usr/bin/env bash
##########################################################################
# Script Name  : write-iso
# Description  : Copies an ISO file to a USB drive using dd
# Dependencies : fzf (optional), zenity (optional)
# Arguments    : see help function
# Author       : Copyright (C) 2023, Richard B. Romig, LudditeGeek@Mosfanet
# Email        : rick.romig@gmail.com | rick.romig@mymetronet.net
# Created      : 18 Feb 2023
# Updated      : 17 Feb 2025
# Comments     : Testing indicates USB drive need to be mounted.
#              : Works with fuzzy finder (fzf) or zenity, if installed.
#              : To test without writing to USB drive, use the -d option to enable a dryrun.
#              : After a dryrun, USB drive will not be unmounted.
# TODO (Rick)  :
# # License      : GNU General Public License, version 2.0

# Copyright © 2025, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
##########################################################################

## Shellcheck Directives ##
# shellcheck source=/home/rick/bin/functionlib

## Load function library ##

if [[ -x "$HOME/bin/functionlib" ]]; then
  source "$HOME/bin/functionlib"
else
  printf "\e[91mERROR:\e[0m functionlib not found!\n" >&2
  exit 1
fi

## Global Variables ##

script=$(basename "$0"); readonly script
readonly version="6.5.25048"
user=$(whoami); readonly user
dryrun="$FALSE"

## Functions ##

help() {
  local errcode updated
	errcode="${1:-2}"
	updated="17 Feb 2025"
	cat << _HELP_
${orange}$script${normal} $version, Upated: $updated
Writes ISO to a USB drive

${green}Usage:${normal} $script [OPTION]

${orange}Available options:${normal}
  -d  Enable Dry Run simulation (-dw for a dry run)
  -h  Show this help message and exit
  -w  Write ISO to USB device (-dw for a dry run)

_HELP_
  exit "$errcode"
}

check_usb_drive() {
	[[ $(lsblk -S -o TRAN | grep 'usb') = *usb* ]] || diehard "No USB drive connected." "Insert and mount the target USB drive." "$script v$version"
}

select_iso() {
	local isofile iso_d
	iso_d="$HOME/Downloads/ISO/"
	isofile=$(find "$iso_d" -maxdepth 3 -type f -iname "*.iso" -print | sort -d | fzf --height 75% --reverse --prompt "Select the ISO file to write: ")
	echo "$isofile"
}

select_usb() {
	local usb_device
	usb_device=$(lsblk -o HOTPLUG,TYPE,NAME,SIZE,LABEL | awk '$2 == "disk" && $1 == "1" {print $0}' | awk '{$1=$1}1' | sed 's/1//' | fzf --height 40% --reverse --prompt "Select the USB drive to write to: ")
	usb_device=$(echo "$usb_device" | awk '{print $2}')
	echo "$usb_device"
}

mount_usb() {
	local mount_name usbpart
	mount_name="$1"
	usbpart="$2"
  [[ -d "/media/$user/$mount_name" ]] || sudo mkdir -p "/media/$user/$mount_name"
	sudo mount "/dev/$usbpart" "/media/$user/$mount_name" 2>/dev/null
	printf "USB drive /dev/%s is mounted at /media/$user/%s\n" "$usbpart" "$mount_name"
}

unmount_usb() {
	local mount_name usbpart
	mount_name="$1"
	usbpart="$2"
	sudo umount "/dev/$usbpart" && printf "USB drive unmounted.\n" # /media/$user/"$mount_name"
	[[ -d "/media/$user/$mount_name" ]] && sudo rmdir "/media/$user/$mount_name"
	printf "It's now safe to remove the USB drive.\n"
}

simulate_dd() {
  local iso usb mount_name
	iso="$1"
	usb="$2"
	mount_name="$3"
  printf "\nWriting %s to /dev/%s (SIMULATED) ...\n" "$(basename "$iso")" "$usb"
  spin
  sleep 10
  kill "$!"
  tput cnorm
  printf "\n%s written to /dev/%s (SIMULATED)\n"  "$(basename "$iso")" "$usb"
  printf "\nContents of /dev/%s:\n" "$usb"
	printf "Disk label: %s\n" "$mount_name"
  ls -F "/media/$user/$mount_name"
}

write_dd() {
  local iso usb mount_name
	iso="$1"
	usb="$2"
	mount_name="$3"
	printf "\nWriting %s to /dev/%s...\n" "$(basename "$iso")" "$usb"
	if sudo dd if="$iso" of="/dev/$usb" bs=16M status=progress oflag=sync; then
	  printf "%s written to /dev/%s.\n" "$(basename "$iso")" "$usb"
    printf "\nContents of /dev/%s\n\n" "$usb"
		printf "Disk label: %s\n" "$mount_name"
    ls -F "/media/$user/$mount_name"
	else
    diehard "$iso write to /dev/$usb failed.\n" "$script v$version"
  fi
}

write_iso() {
	local isofile usbdevice usbpart mount_name
	isofile="$1"
	usbdevice="$2"
	printf "%-16s %s\n" "Selected ISO:" "$(basename "$isofile")"
	printf "%-16s /dev/%s\n" "Selected device:" "$usbdevice"

	# Mount selected USB drive if not already mounted.
	usbpart="${usbdevice}1"
	if mount | grep -q "$usbpart" > /dev/null 2>&1; then
		mount_name=$(lsblk | grep "$usbpart" | cut -d'/' -f4- )
	else
		sudo_login 2
		mount_name="$(date +%y%b%d)"
		mount_usb "$usbpart"
	fi
	printf "Current contents of /dev/%s:\n" "$usbdevice"
	printf "Disk label: %s\n" "$mount_name"
	ls -F "/media/$user/$mount_name"
	# Confirm action or cancel
	if [[ "$dryrun" == "$TRUE" ]]; then
		simulate_dd "$isofile" "$usbdevice" "$mount_name"
	else
		printf "\n%sIf you continue, ALL data will be erased from device %s.%s\n\n" "$orange" "$usbdevice" "$normal"
		printf "Answer 'yes' only if you are %s%sABSOLUTELY%s sure you want to proceed.\n\n" "$bold" "$orange" "$normal"
		if yes_or_no "Write $(basename "$isofile") to /dev/$usb_device?"; then
			sudo_login 2
			write_dd "$isofile" "$usbdevice" "$mount_name"
			printf "Unmounting the USB Drive from /dev/%s/%s\n" "$user"  "$mount_name"
			mount | grep -q "/dev/$usbpart" > /dev/null 2>&1 && unmount_usb "$mount_name" "$usbpart"
		else
		printf "Operation canceled. No action taken.\n"
		fi
	fi
}

main() {
  local noOpt opt optstr iso_file usb_device
	noOpt=1
	optstr=":dhw"
	while getopts "$optstr" opt; do
		case "$opt" in
			d )
				dryrun="$TRUE"
				printf "%sPerforming a dryrun. The ISO will NOT be written to USB drive.%s\n\n" "$orange" "$normal"
			;;
			h )
				help 0
			;;
			w )
				box "$script v$version"
				printf "Writes ISO to a USB drive.\n\n"
				check_package fzf
				check_usb_drive
				iso_file=$(select_iso)
				usb_device=$(select_usb)
				write_iso "$iso_file" "$usb_device"
			;;
			? )
				printf "%s Invalid option: -%s\n" "$RED_ERROR" "$OPTARG" >&2
				help 2
		esac
		noOpt=0
	done
	[[ "$noOpt" = 1 ]] && { printf "%s No argument passed.\n" "$RED_ERROR" >&2; help 1; }
	shift "$(( OPTIND - 1 ))"
	exit
}

## Execution ##

main "$@"
