#!/bin/bash
################################################################################
# Script Name  : yt-dl-install
# Description  : Installs/updates youtube-dl from https://yt-dl.org
# Dependencies : apt, chmod, curl, dpkg
# Arguments    : -i or --info to dispaly information about the script.
# Author       : Richard B. Romig, 23 May 2019
# Email        : rick.romig@gmail.com
# Comment      : Removes package manager installed version from /usr/bin/
################################################################################
# GPL v2
# Copyright (C) 2019, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
################################################################################

readonly SCRIPT=$(basename "$0")
readonly VERSION="1.2.0"
readonly UPDATED="20 Sep 2019"

BINDIR=$HOME"/bin"

show_info()
{
  cat << _EOF_
$SCRIPT $VERSION

1, $SCRIPT installs the most current version of youtude-dl from the
youtube-dl GitHub site at https://ytdl-org.github.io/youtube-dl/index.html.
Portions of this script are based upon the download instructions on the project's
download page.

2, The script was written for Debian and Ubuntu based distributions but your
experience may vary.

3. The youtube-dl packages contained in the Debian and Ubuntu repositories are
often older and are not regurlarly updated whereas the version on yt-dl.org is
updated quite regurlarly (usually monthly, if not more often).

4. The version installed by the package manager usually places the application
in '/usr/bin/' and it can't updated unless the version in the repository for
your distribution is updated.

5. The script will first remove the version installed to 'usr/bin' by the package
manager (if installed) and install the most current version from yt-dl.org to
'/usr/local/bin'.

6. If a version downloaded from yt-dl.org is already installed, it will display
the version number and attempt to update it to the latest version.

7. During the installation of youtube-dl from yt-dl.org, the script will install
a script in /etc/cron.daily that will use anacron to automatically check for
updates

8. Please review the README.md, LICENSE, and WARRANTY in the downloaded ZIP
archive for more information. They can also be reviewed in my GitHub repository
at: https://github.com/RickRomig/bashscripts

Richard Romig (GNU/General Public License version 2.0)

_EOF_
}

exists()
{
  command -v "$1" >/dev/null 2>&1
}

# Display information about the script

if [ "$1" == "-i" ] || [ "$1" == "--info" ]; then
  show_info
  exit
fi

# Check sudo access and start sudo timer

sudo ls > /dev/null 2>&1

# Install curl, if not installed.

dpkg -l | grep -qw curl || sudo apt install -yyq curl

# Header

echo "$SCRIPT v$VERSION (Updated: $UPDATED)"
echo "youtube-dl installer and updater"
echo "Copyright (c) 2019, Richard Romig"
echo "Licensed under the GNU/General Public License version 2.0"

# Delete older version from /usr/bin/ that was installed from the repositories

if dpkg -l | grep -qw youtube-dl
then
  echo "Removing the older version installed from the distribution repositories..."
  sudo apt purge -yyq youtube-dl
fi

# Check if youtube-dl is installed from https://yt-dl.org

if exists youtube-dl
then
  # Check version and update
  echo "youtube-dl version: $(youtube-dl --version)"
  echo $'\n'$"Updating youtube-dl to the newest version..."
  sudo youtube-dl -U
else
  # Download youtube-dl to /usr/local/bin/
  echo "Installing youtube-dl from https://yt-dl.org..."
  if sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl \
    -o /usr/local/bin/youtube-dl
  then
    # Set permissions on the downloaded file
    sudo chmod a+rx /usr/local/bin/youtube-dl
    echo "youtube-dl version $(youtube-dl --version) installed to /usr/local/bin"
    # Copy automatic updater for anacron update
    if [ -x "$BINDIR/z-ytdlupdate" ]; then
      echo "Copying z-ytdlupdate to /etc/cron.daily/"
      echo "Log file locaton: /var/log/ytdlup.log"
      sudo cp "$BINDIR/z-ytdlupdate" /etc/cron.daily/
    else
      echo "~/bin/z-ytdlupdate not present. Manually update with:"
      echo -e "\e[1;33msudo youtube-dl -U\e[0m"
    fi
  else
    STATUS="$?"
    echo -e "\e[1;31myoutube-dl download failed. Exit code: $STATUS\e[0m" >&2
  fi
fi

exit

