#!/bin/sh
###############################################################################
# Script Name  : yt-dl-update
# Description  : Updates ytdl.org version of youtube-dl
# Dependencies : youtube-dl
# Arguments    : none
# Author       : Richard B. Romig, 01 September 2019
# Email        : rick.romig@gmail.com
# Comments     : anacron or cron script to automatically update youtube-dl
#              : To run with anacron, sudo cp yt=dl-update /etc/cron.weekly
#              : Or use crontab to add to cron jobs
# Last updated : 20 Sep 2019
###############################################################################
# GPL v2
# Copyright (C) 2019, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
################################################################################

set -e

youtube-dl -U > /dev/null 2>&1
