#!/bin/sh

# anacron or cron script to automatically update youtube-dl
# To run with anacron, sudo cp yt=dl-update /etc/cron.weekly
# Or use crontab to add to cron jobs

set -e

youtube-dl -U > /dev/null 2>&1

