#!/bin/bash
###############################################################################
# Script Name  : yt-dl-remove
# Description  : Remove youtube-dl, configuration files, and logs.
# Dependencies : apt
# Arguments    : none
# Author       : Richard B. Romig, 17 July 2019
# Email        : rick.romig@gmail.com
# Comments     :
# Last updated : 20 Sep 2019
###############################################################################
# GPL v2
# Copyright (C) 2019, Richard B. Romig
# Email: rick.romig@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
################################################################################

readonly SCRIPT=$(basename "$0")
readonly VERSION="1.2.0"
readonly UPDATED="20 Sep 2019"

readonly HOMEDIR=$HOME

show_info()
{
   cat << _EOF_
$SCRIPT completely removes Youtube-dl, both the version installed from your
distribution repositories and the version downloaded from https:yt-dl.org. In
the latter case, the script will also remove the ~/.config/youtube-dl/conf and
and /etc/youtube-dl.conf configuration files. Additionally, the z-ytdlupdate
script, if installed, will be remvoed from the appropriate /etc/cron directory
and its log file from /var/log.
_EOF_
}

exists()
{
  command -v "$1" >/dev/null 2>&1
}

rm_repo()
{
  # Remove version from distribution repositories, if installed
  if dpkg -l | grep -qw youtube-dl
  then
    echo "Removing youtube-dl $(youtube-dl --version) installed from the repositories..."
    sudo apt purge -yyq youtube-dl
   else
    echo "Repository version of youtube-dl not installed."
  fi
}

rm_ytdl()
{
  # Remove yt-dl.org version, if installed
  if exists youtube-dl
  then
    echo "Removing youtube-dl $(youtube-dl --version) installed from https://yt-dl.org..."
    sudo rm  /usr/local/bin/youtube-dl
  else
    echo "ytdl.org version of youtube-dl not installed."
  fi
}

rm_cfg()
{
  # Remove configuration files, if they exist
  if [ -f "$HOMEDIR/.config/youtube-dl/conf" ]; then
    echo "Removing user youtube-dl configuration file..."
    rm -rf "$HOMEDIR/.config/youtube.dl/"
  fi

  if [ -f "/etc/youtube-dl.conf" ]; then
    echo "Removing global youtube-dl configuration file..."
    sudo rm "/etc/youtube-dl.conf"
  fi
  echo "youtube-dl configuration files removed."
}

rm_updater()
{
  # Remove the update script if it exists
  if [ -x /etc/cron.daily/z-ytdlupdate ]; then
    sudo rm -f /etc/cron.daily/z-ytdlupdate
    echo "youtube-dl update script removed."
  elif [ -x /etc/cron.weekly/z-ytdlupdate ]; then
    sudo rm -f /etc/cron.weekly/z-ytdlupdate
    echo "youtube-dl update script removed."
  elif  [ -x /etc/cron.monthly/z-ytdlupdate ]; then
    sudo rm -f /etc/cron.monthly/z-ytdlupdate
    echo "youtube-dl update script removed."
  else
     echo "youtube-dl update script not found."
  fi
}

rm_logs()
{
  # Remove update log file if it exists
  if [ -f /var/log/ytdlup.log ]; then
    sudo rm /var/log/ytdlup.log
    echo "youtube-dl update log file removed."
  else
    echo "No youtube-dl log files found."
  fi
}

# Display information about the script

if [ "$1" = "-i" ] || [ "$1" = "--info" ]; then
  show_info
  exit
fi

echo "$SCRIPT v$VERSION (Updated: $UPDATED)"
echo "This script removes youtube-dl and its configuration files."
echo "It removes both the version installed through the distribution's"
echo "repositories and the version downloaded from https://ytdl.org"

read -rp "Are you sure you want to completely remove youtube-dl? [yN] " CHOICE
case $CHOICE in
  [Yy]*)
    rm_repo
    rm_ytdl
    rm_cfg
    rm_updater
    rm_logs
    ;;
  *)  echo "Nothing to do. Exiting the script." ;;
esac

exit

